import type { Lesson } from '../types/lesson';
import {
  countProduct,
  permutations,
  combinations,
  multinomialArrangements,
  starsAndBars,
  derangementProbability,
  expectedFixedPoints,
} from '../lib/probability';

export const combinatoricsLessons: Lesson[] = [
  {
    id: 's2-multiplication',
    index: 0,
    title: 'The Multiplication Principle',
    concept: 'Choices multiply across stages',
    status: 'built',
    prerequisiteId: null,
    steps: [
      {
        id: 's2-multiplication-s1',
        type: 'concept',
        title: 'Counting by stages',
        body: 'When a choice is made in independent stages, the totals multiply. Press count and watch one dot appear for every distinct outcome as the product builds.',
        simulation: 'countingTree',
        simConfig: { slots: 2, o0: 3, o1: 4 },
        lecture: [
          {
            heading: 'Rule of product',
            text: 'If a process has independent stages with $n_1, n_2, \\dots, n_k$ choices, the number of complete outcomes is their product. Each earlier choice fans out into all the later ones.',
            formula: 'N = n_1 \\cdot n_2 \\cdots n_k',
          },
          {
            heading: 'Rule of sum',
            text: 'When outcomes split into mutually exclusive cases instead of stages, you add the cases. "And" (stages) multiplies; "or" (cases) adds.',
          },
          {
            heading: 'With or without repetition',
            text: 'If a choice can repeat (like digits in a PIN), every stage keeps the full menu, so it is $n^k$. If items cannot repeat, the menu shrinks by one each stage.',
            formula: 'n^k \\;\\text{vs}\\; n(n-1)(n-2)\\cdots',
          },
          {
            heading: 'Common mistake',
            text: 'Watch for whether repetition is allowed. A 4-digit PIN is $10^4$, not $10\\cdot 9\\cdot 8\\cdot 7$ — digits may repeat.',
          },
        ],
      },
      {
        id: 's2-multiplication-s2',
        type: 'problem',
        title: 'Outfits',
        body: 'You have 3 shirts and 4 pairs of pants.',
        simulation: 'countingTree',
        simConfig: { slots: 2, o0: 3, o1: 4 },
        question: 'How many distinct outfits can you make? (a whole number)',
        answer: countProduct([3, 4]),
        tolerance: 0.5,
        unit: 'outfits',
        feedback: {
          correct: 'Right — 3 × 4 = 12 outfits, one for each shirt-and-pants pairing.',
          incorrect: 'Multiply the choices at each stage: 3 shirts × 4 pants = 12.',
        },
      },
      {
        id: 's2-multiplication-s3',
        type: 'problem',
        title: 'Add shoes',
        body: 'Now add 2 pairs of shoes to the 3 shirts and 4 pairs of pants.',
        simulation: 'countingTree',
        simConfig: { slots: 3, o0: 3, o1: 4, o2: 2 },
        question: 'How many shirt-pants-shoes outfits are there? (a whole number)',
        answer: countProduct([3, 4, 2]),
        tolerance: 0.5,
        unit: 'outfits',
        feedback: {
          correct: 'Exactly — 3 × 4 × 2 = 24. Each new independent stage multiplies the total.',
          incorrect: 'Multiply all three stages: 3 × 4 × 2 = 24.',
        },
      },
      {
        id: 's2-multiplication-s4',
        type: 'problem',
        title: 'A 4-digit PIN',
        body: 'A PIN is 4 digits, each from 0–9, and digits may repeat.',
        simulation: 'countingTree',
        simConfig: { slots: 4, o0: 10, o1: 10, o2: 10, o3: 10 },
        question: 'How many PINs are possible? (a whole number)',
        answer: countProduct([10, 10, 10, 10]),
        tolerance: 0.5,
        unit: 'PINs',
        feedback: {
          correct: 'Right — repetition is allowed, so it is 10⁴ = 10,000.',
          incorrect: 'Digits can repeat, so every slot has 10 options: 10⁴ = 10,000 (not 10·9·8·7).',
        },
      },
      {
        id: 's2-multiplication-s5',
        type: 'problem',
        title: 'A four-course meal',
        body: 'A menu offers 2 appetizers, 3 mains, 2 sides, and 5 desserts; you pick one of each.',
        simulation: 'countingTree',
        simConfig: { slots: 4, o0: 2, o1: 3, o2: 2, o3: 5 },
        question: 'How many distinct meals are possible? (a whole number)',
        answer: countProduct([2, 3, 2, 5]),
        tolerance: 0.5,
        unit: 'meals',
        feedback: {
          correct: 'Exactly — 2 × 3 × 2 × 5 = 60 meals.',
          incorrect: 'Multiply every course: 2 × 3 × 2 × 5 = 60.',
        },
      },
      {
        id: 's2-multiplication-s6',
        type: 'problem',
        title: 'License plates',
        body: 'A plate is 2 letters (A–Z) followed by 3 digits (0–9), repetition allowed.',
        simulation: 'countingTree',
        simConfig: { slots: 5, o0: 26, o1: 26, o2: 10, o3: 10, o4: 10 },
        question: 'How many plates are possible? (a whole number)',
        answer: countProduct([26, 26, 10, 10, 10]),
        tolerance: 0.5,
        unit: 'plates',
        feedback: {
          correct: 'Right — 26² × 10³ = 676,000 plates.',
          incorrect: 'Multiply each slot: 26 × 26 × 10 × 10 × 10 = 676,000.',
        },
      },
    ],
  },
  {
    id: 's2-permutations',
    index: 0,
    title: 'Permutations',
    concept: 'Counting ordered arrangements',
    status: 'built',
    prerequisiteId: null,
    steps: [
      {
        id: 's2-permutations-s1',
        type: 'concept',
        title: 'When order matters',
        body: 'A permutation is an ordered arrangement. Filling the first slot uses up an item, so the next slot has one fewer choice. Count the arrangements and watch them tally up.',
        simulation: 'arrangements',
        simConfig: { n: 4, r: 4 },
        lecture: [
          {
            heading: 'Arranging all n',
            text: 'The number of orderings of $n$ distinct items is $n!$ — there are $n$ choices for the first position, $n-1$ for the second, and so on down to 1.',
            formula: 'n! = n(n-1)(n-2)\\cdots 1',
          },
          {
            heading: 'Arranging r of n',
            text: 'To fill $r$ ordered slots from $n$ items, multiply the first $r$ descending factors. This is the permutation count $nPr$.',
            formula: 'nPr = \\frac{n!}{(n-r)!}',
          },
          {
            heading: 'Common mistake',
            text: 'Permutations count order. If rearranging the same items does not create a new outcome (a committee, a hand of cards), you want combinations instead.',
          },
        ],
      },
      {
        id: 's2-permutations-s2',
        type: 'problem',
        title: 'Line them up',
        body: 'Four distinct books are placed in a row on a shelf.',
        simulation: 'arrangements',
        simConfig: { n: 4, r: 4 },
        question: 'How many orderings are there? (a whole number)',
        answer: permutations(4, 4),
        tolerance: 0.5,
        unit: 'orderings',
        feedback: {
          correct: 'Right — 4! = 24 orderings.',
          incorrect: 'Arrange all 4: 4! = 4 × 3 × 2 × 1 = 24.',
        },
      },
      {
        id: 's2-permutations-s3',
        type: 'problem',
        title: 'Pick and order',
        body: 'From 5 runners, you record who finishes 1st, 2nd, and 3rd.',
        simulation: 'arrangements',
        simConfig: { n: 5, r: 3 },
        question: 'How many ordered podiums are possible? (a whole number)',
        answer: permutations(5, 3),
        tolerance: 0.5,
        unit: 'podiums',
        feedback: {
          correct: 'Exactly — 5 × 4 × 3 = 60 = 5P3.',
          incorrect: 'Fill 3 ordered slots from 5: 5 × 4 × 3 = 60.',
        },
      },
      {
        id: 's2-permutations-s4',
        type: 'problem',
        title: 'Six in a row',
        body: 'Six distinct paintings are hung in a row.',
        simulation: 'arrangements',
        simConfig: { n: 6, r: 6 },
        question: 'How many arrangements are there? (a whole number)',
        answer: permutations(6, 6),
        tolerance: 0.5,
        unit: 'arrangements',
        feedback: {
          correct: 'Right — 6! = 720.',
          incorrect: 'Arrange all 6: 6! = 720.',
        },
      },
      {
        id: 's2-permutations-s5',
        type: 'problem',
        title: 'Medals',
        body: 'Eight sprinters compete for gold, silver, and bronze (order matters).',
        simulation: 'arrangements',
        simConfig: { n: 8, r: 3 },
        question: 'How many ways can the three medals be awarded? (a whole number)',
        answer: permutations(8, 3),
        tolerance: 0.5,
        unit: 'ways',
        feedback: {
          correct: 'Exactly — 8 × 7 × 6 = 336 = 8P3.',
          incorrect: 'Order matters: 8 × 7 × 6 = 336.',
        },
      },
      {
        id: 's2-permutations-s6',
        type: 'problem',
        title: 'Seven seats',
        body: 'Seven guests sit in seven distinct chairs.',
        simulation: 'arrangements',
        simConfig: { n: 7, r: 7 },
        question: 'How many seatings are possible? (a whole number)',
        answer: permutations(7, 7),
        tolerance: 0.5,
        unit: 'seatings',
        feedback: {
          correct: 'Right — 7! = 5,040.',
          incorrect: 'Arrange all 7: 7! = 5,040.',
        },
      },
    ],
  },
  {
    id: 's2-combinations',
    index: 0,
    title: 'Combinations & Pascal’s Triangle',
    concept: 'Choosing without order',
    status: 'built',
    prerequisiteId: null,
    steps: [
      {
        id: 's2-combinations-s1',
        type: 'concept',
        title: 'When order does not matter',
        body: 'A combination counts selections where order is irrelevant. Each cell of Pascal’s triangle is a count of subsets — find C(n, k) and watch the triangle fill in.',
        simulation: 'pascal',
        simConfig: { n: 5, k: 2 },
        lecture: [
          {
            heading: 'Choose k of n',
            text: 'The number of ways to choose $k$ items from $n$, ignoring order, divides the ordered count $nPr$ by the $k!$ orderings of each selection.',
            formula: 'nCk = \\binom{n}{k} = \\frac{n!}{k!\\,(n-k)!}',
          },
          {
            heading: 'Pascal’s triangle',
            text: 'Each entry is the sum of the two above it, because a chosen item is either in or out of a subset. Row $n$ lists $\\binom{n}{0}, \\dots, \\binom{n}{n}$.',
            formula: '\\binom{n}{k} = \\binom{n-1}{k-1} + \\binom{n-1}{k}',
          },
          {
            heading: 'Symmetry',
            text: 'Choosing the $k$ you keep is the same as choosing the $n-k$ you leave out, so the triangle is symmetric.',
            formula: '\\binom{n}{k} = \\binom{n}{n-k}',
          },
          {
            heading: 'Common mistake',
            text: 'If swapping two chosen items makes a new outcome, order matters — use permutations. Combinations are for unordered selections.',
          },
        ],
      },
      {
        id: 's2-combinations-s2',
        type: 'problem',
        title: 'Pick a pair',
        body: 'From 5 friends, you choose 2 to invite (order does not matter).',
        simulation: 'pascal',
        simConfig: { n: 5, k: 2 },
        question: 'How many pairs are possible? (a whole number)',
        answer: combinations(5, 2),
        tolerance: 0.5,
        unit: 'pairs',
        feedback: {
          correct: 'Right — C(5, 2) = 10.',
          incorrect: 'Order does not matter: C(5, 2) = 10.',
        },
      },
      {
        id: 's2-combinations-s3',
        type: 'problem',
        title: 'A committee',
        body: 'A committee of 3 is chosen from 6 people.',
        simulation: 'pascal',
        simConfig: { n: 6, k: 3 },
        question: 'How many committees are possible? (a whole number)',
        answer: combinations(6, 3),
        tolerance: 0.5,
        unit: 'committees',
        feedback: {
          correct: 'Exactly — C(6, 3) = 20.',
          incorrect: 'Choose 3 of 6 without order: C(6, 3) = 20.',
        },
      },
      {
        id: 's2-combinations-s4',
        type: 'problem',
        title: 'Symmetry',
        body: 'You must choose 5 of 7 toppings to LEAVE OFF a pizza.',
        simulation: 'pascal',
        simConfig: { n: 7, k: 5 },
        question: 'How many choices are there? (a whole number)',
        answer: combinations(7, 5),
        tolerance: 0.5,
        unit: 'choices',
        feedback: {
          correct: 'Right — C(7, 5) = C(7, 2) = 21. Leaving 5 off is the same as keeping 2.',
          incorrect: 'By symmetry C(7, 5) = C(7, 2) = 21.',
        },
      },
      {
        id: 's2-combinations-s5',
        type: 'problem',
        title: 'A larger choice',
        body: 'A team of 3 is chosen from 10 players.',
        simulation: 'pascal',
        simConfig: { n: 10, k: 3 },
        question: 'How many teams are possible? (a whole number)',
        answer: combinations(10, 3),
        tolerance: 0.5,
        unit: 'teams',
        feedback: {
          correct: 'Exactly — C(10, 3) = 120.',
          incorrect: 'Choose 3 of 10: C(10, 3) = 120.',
        },
      },
      {
        id: 's2-combinations-s6',
        type: 'problem',
        title: 'Five of twelve',
        body: 'Five books are chosen from a shelf of 12 to take on a trip.',
        simulation: 'pascal',
        simConfig: { n: 12, k: 5 },
        question: 'How many selections are possible? (a whole number)',
        answer: combinations(12, 5),
        tolerance: 0.5,
        unit: 'selections',
        feedback: {
          correct: 'Right — C(12, 5) = 792.',
          incorrect: 'Choose 5 of 12 without order: C(12, 5) = 792.',
        },
      },
    ],
  },
  {
    id: 's2-anagrams',
    index: 0,
    title: 'Arrangements with Repeats',
    concept: 'Permutations of a multiset',
    status: 'built',
    prerequisiteId: null,
    steps: [
      {
        id: 's2-anagrams-s1',
        type: 'concept',
        title: 'Dividing out the repeats',
        body: 'When some items are identical, swapping them does not make a new arrangement. Start from n! and divide by the orderings of each repeated group.',
        simulation: 'arrangements',
        simConfig: { multiset: 1, groups: 3, c0: 1, c1: 2, c2: 1 },
        lecture: [
          {
            heading: 'Multiset permutations',
            text: 'Arranging $n$ items where the groups have sizes $n_1, \\dots, n_k$ gives the multinomial count: $n!$ divided by the factorial of each group size, removing the indistinguishable rearrangements.',
            formula: '\\frac{n!}{n_1!\\,n_2! \\cdots n_k!}',
          },
          {
            heading: 'Why divide',
            text: 'Each distinct arrangement is counted $n_1!\\,n_2!\\cdots$ times by $n!$ — once for every internal shuffle of the identical letters — so dividing collapses them to one.',
          },
          {
            heading: 'Common mistake',
            text: 'Divide by every repeated group, not just one. Forgetting a group leaves the count too large.',
          },
        ],
      },
      {
        id: 's2-anagrams-s2',
        type: 'problem',
        title: 'BOOK',
        body: 'Rearrange the letters of BOOK (two O’s).',
        simulation: 'arrangements',
        simConfig: { multiset: 1, groups: 3, c0: 1, c1: 2, c2: 1 },
        question: 'How many distinct arrangements are there? (a whole number)',
        answer: multinomialArrangements([1, 2, 1]),
        tolerance: 0.5,
        unit: 'arrangements',
        feedback: {
          correct: 'Right — 4!/2! = 12. The two O’s are interchangeable.',
          incorrect: 'Divide out the repeated O’s: 4!/2! = 12.',
        },
      },
      {
        id: 's2-anagrams-s3',
        type: 'problem',
        title: 'LEVEL',
        body: 'Rearrange the letters of LEVEL (two L’s, two E’s).',
        simulation: 'arrangements',
        simConfig: { multiset: 1, groups: 3, c0: 2, c1: 2, c2: 1 },
        question: 'How many distinct arrangements are there? (a whole number)',
        answer: multinomialArrangements([2, 2, 1]),
        tolerance: 0.5,
        unit: 'arrangements',
        feedback: {
          correct: 'Exactly — 5!/(2!·2!) = 30.',
          incorrect: 'Divide by both repeated pairs: 5!/(2!·2!) = 30.',
        },
      },
      {
        id: 's2-anagrams-s4',
        type: 'problem',
        title: 'BANANA',
        body: 'Rearrange the letters of BANANA (three A’s, two N’s).',
        simulation: 'arrangements',
        simConfig: { multiset: 1, groups: 3, c0: 1, c1: 3, c2: 2 },
        question: 'How many distinct arrangements are there? (a whole number)',
        answer: multinomialArrangements([1, 3, 2]),
        tolerance: 0.5,
        unit: 'arrangements',
        feedback: {
          correct: 'Right — 6!/(3!·2!) = 60.',
          incorrect: 'Divide by the A’s and N’s: 6!/(3!·2!) = 60.',
        },
      },
      {
        id: 's2-anagrams-s5',
        type: 'problem',
        title: 'Three teams',
        body: 'Nine students are split into labeled teams of 4, 3, and 2.',
        simulation: 'arrangements',
        simConfig: { multiset: 1, groups: 3, c0: 4, c1: 3, c2: 2 },
        question: 'How many ways can the split be made? (a whole number)',
        answer: multinomialArrangements([4, 3, 2]),
        tolerance: 0.5,
        unit: 'ways',
        feedback: {
          correct: 'Exactly — 9!/(4!·3!·2!) = 1,260, the multinomial coefficient.',
          incorrect: 'Use the multinomial: 9!/(4!·3!·2!) = 1,260.',
        },
      },
      {
        id: 's2-anagrams-s6',
        type: 'problem',
        title: 'MISSISSIPPI',
        body: 'Rearrange the letters of MISSISSIPPI (M:1, I:4, S:4, P:2).',
        simulation: 'arrangements',
        simConfig: { multiset: 1, groups: 4, c0: 1, c1: 4, c2: 4, c3: 2 },
        question: 'How many distinct arrangements are there? (a whole number)',
        answer: multinomialArrangements([1, 4, 4, 2]),
        tolerance: 0.5,
        unit: 'arrangements',
        feedback: {
          correct: 'Right — 11!/(1!·4!·4!·2!) = 34,650.',
          incorrect: 'Divide 11! by 4! (I), 4! (S), and 2! (P): 34,650.',
        },
      },
    ],
  },
  {
    id: 's2-stars-bars',
    index: 0,
    title: 'Stars and Bars',
    concept: 'Distributing identical items',
    status: 'built',
    prerequisiteId: null,
    steps: [
      {
        id: 's2-stars-bars-s1',
        type: 'concept',
        title: 'Bars between stars',
        body: 'To split identical items among distinct boxes, place dividers (bars) among the items (stars). Every placement of bars is one distribution — count them.',
        simulation: 'starsBars',
        simConfig: { stars: 5, boxes: 3 },
        lecture: [
          {
            heading: 'The bijection',
            text: 'Writing $n$ identical stars in a row and inserting $k-1$ bars cuts them into $k$ ordered groups — one per box. The number of arrangements of stars and bars is the number of distributions.',
            formula: '\\binom{n + k - 1}{\\,k - 1\\,}',
          },
          {
            heading: 'Why it works',
            text: 'There are $n + k - 1$ positions total; choosing which $k-1$ hold bars (the rest hold stars) fixes the whole arrangement. Empty boxes are allowed — two bars can sit side by side.',
          },
          {
            heading: 'Common mistake',
            text: 'Stars and bars is for identical items in distinct boxes. If the items are distinguishable, count differently (each item independently picks a box).',
          },
        ],
      },
      {
        id: 's2-stars-bars-s2',
        type: 'problem',
        title: 'Candies to kids',
        body: '5 identical candies are handed out to 3 children; a child may get none.',
        simulation: 'starsBars',
        simConfig: { stars: 5, boxes: 3 },
        question: 'How many distributions are possible? (a whole number)',
        answer: starsAndBars(5, 3),
        tolerance: 0.5,
        unit: 'distributions',
        feedback: {
          correct: 'Right — C(5 + 3 − 1, 3 − 1) = C(7, 2) = 21.',
          incorrect: 'Stars and bars: C(7, 2) = 21.',
        },
      },
      {
        id: 's2-stars-bars-s3',
        type: 'problem',
        title: 'Everyone gets one',
        body: 'Now 5 candies go to 3 children, but each child must get at least one.',
        simulation: 'starsBars',
        simConfig: { stars: 2, boxes: 3 },
        question: 'How many distributions are possible? (a whole number)',
        answer: starsAndBars(2, 3),
        tolerance: 0.5,
        unit: 'distributions',
        feedback: {
          correct: 'Exactly — give one to each first, then distribute the remaining 2 freely: C(4, 2) = 6.',
          incorrect: 'Hand out 1 each (uses 3), then share the leftover 2: C(2 + 2, 2) = 6.',
        },
      },
      {
        id: 's2-stars-bars-s4',
        type: 'problem',
        title: 'An equation',
        body: 'Count the nonnegative integer solutions to x + y + z = 8.',
        simulation: 'starsBars',
        simConfig: { stars: 8, boxes: 3 },
        question: 'How many solutions are there? (a whole number)',
        answer: starsAndBars(8, 3),
        tolerance: 0.5,
        unit: 'solutions',
        feedback: {
          correct: 'Right — C(8 + 2, 2) = C(10, 2) = 45.',
          incorrect: '3 variables, sum 8: C(10, 2) = 45.',
        },
      },
      {
        id: 's2-stars-bars-s5',
        type: 'problem',
        title: 'Four boxes',
        body: '6 identical balls are placed into 4 distinct boxes (empties allowed).',
        simulation: 'starsBars',
        simConfig: { stars: 6, boxes: 4 },
        question: 'How many placements are possible? (a whole number)',
        answer: starsAndBars(6, 4),
        tolerance: 0.5,
        unit: 'placements',
        feedback: {
          correct: 'Exactly — C(6 + 3, 3) = C(9, 3) = 84.',
          incorrect: 'Stars and bars with 3 dividers: C(9, 3) = 84.',
        },
      },
      {
        id: 's2-stars-bars-s6',
        type: 'problem',
        title: 'Ten to four',
        body: '10 identical coins are split among 4 distinct jars (empties allowed).',
        simulation: 'starsBars',
        simConfig: { stars: 10, boxes: 4 },
        question: 'How many ways are there? (a whole number)',
        answer: starsAndBars(10, 4),
        tolerance: 0.5,
        unit: 'ways',
        feedback: {
          correct: 'Right — C(10 + 3, 3) = C(13, 3) = 286.',
          incorrect: 'Stars and bars: C(13, 3) = 286.',
        },
      },
    ],
  },
  {
    id: 's2-derangements',
    index: 0,
    title: 'Derangements',
    concept: 'When nothing lands right',
    status: 'built',
    prerequisiteId: null,
    steps: [
      {
        id: 's2-derangements-s1',
        type: 'concept',
        title: 'The hat-check problem',
        body: 'n people drop off hats and get them back at random. Shuffle many times and watch the fraction where NOBODY gets their own hat settle near 1/e ≈ 0.368.',
        simulation: 'matching',
        simConfig: { n: 5, metric: 0, trials: 4000 },
        lecture: [
          {
            heading: 'Derangements',
            text: 'A derangement is a permutation with no fixed point — nothing in its original place. By inclusion–exclusion, the probability of a derangement is an alternating sum.',
            formula: 'P(\\text{no match}) = \\sum_{i=0}^{n} \\frac{(-1)^i}{i!} \\;\\to\\; \\frac{1}{e}',
          },
          {
            heading: 'Surprisingly stable',
            text: 'Intuition says big $n$ makes a derangement rare, but the probability hardly moves: it is about 0.368 for every $n \\ge 4$.',
          },
          {
            heading: 'Expected matches',
            text: 'Even though a perfect mismatch is common, the expected number of people who DO get their own hat is exactly 1, for every $n$ — a preview of indicator variables.',
          },
        ],
      },
      {
        id: 's2-derangements-s2',
        type: 'problem',
        title: 'Three hats',
        body: '3 hats are returned at random.',
        simulation: 'matching',
        simConfig: { n: 3, metric: 0, trials: 5000 },
        question: 'What is the probability nobody gets their own hat? (decimal)',
        answer: derangementProbability(3),
        tolerance: 0.05,
        unit: 'probability',
        feedback: {
          correct: 'Right — 1 − 1 + 1/2 − 1/6 = 1/3 ≈ 0.333.',
          incorrect: 'Alternating sum to n = 3: 1 − 1 + 1/2 − 1/6 = 1/3 ≈ 0.333.',
        },
      },
      {
        id: 's2-derangements-s3',
        type: 'problem',
        title: 'Four hats',
        body: '4 hats are returned at random.',
        simulation: 'matching',
        simConfig: { n: 4, metric: 0, trials: 6000 },
        question: 'What is the probability of no match? (decimal)',
        answer: derangementProbability(4),
        tolerance: 0.05,
        unit: 'probability',
        feedback: {
          correct: 'Exactly — through n = 4 the sum is 0.375, already near 1/e.',
          incorrect: 'Continue the alternating sum to 1/4!: ≈ 0.375.',
        },
      },
      {
        id: 's2-derangements-s4',
        type: 'problem',
        title: 'Expected matches',
        body: 'With 5 hats returned at random, count how many people get their OWN hat, on average.',
        simulation: 'matching',
        simConfig: { n: 5, metric: 1, trials: 6000 },
        question: 'What is the expected number of matches? (a number)',
        answer: expectedFixedPoints(5),
        tolerance: 0.12,
        unit: 'matches',
        feedback: {
          correct: 'Right — exactly 1, no matter how many hats. Each person matches with probability 1/n, and there are n of them.',
          incorrect: 'By linearity, n people each match with probability 1/n, so the expected count is 1.',
        },
      },
      {
        id: 's2-derangements-s5',
        type: 'problem',
        title: 'Seven hats',
        body: '7 hats are returned at random.',
        simulation: 'matching',
        simConfig: { n: 7, metric: 0, trials: 8000 },
        question: 'What is the probability of no match? (decimal)',
        answer: derangementProbability(7),
        tolerance: 0.05,
        unit: 'probability',
        feedback: {
          correct: 'Exactly — about 0.368, essentially 1/e. More hats barely changes it.',
          incorrect: 'The derangement probability has converged to 1/e ≈ 0.368.',
        },
      },
    ],
  },
];
