import type { Lesson } from '../types/lesson';
import { totalProbability, bayesPosterior } from '../lib/probability';

const firstPositive = bayesPosterior(0.01, 0.9, 0.9);

export const conditionalLessons: Lesson[] = [
  {
    id: 's3-total-probability',
    index: 0,
    title: 'Law of Total Probability',
    concept: 'Average over the cases',
    status: 'built',
    prerequisiteId: null,
    steps: [
      {
        id: 's3-total-probability-s1',
        type: 'concept',
        title: 'Split, weight, recombine',
        body: 'Pick an urn at random, then draw a ball. To find the overall chance of a target ball, weight each urn’s rate by how often that urn is chosen. Run the two-stage draw and watch the fraction settle.',
        simulation: 'urnTree',
        simConfig: { urns: 2, w0: 1, p0: 0.8, w1: 1, p1: 0.2, trials: 1500 },
        lecture: [
          {
            heading: 'Partition the sample space',
            text: 'Split all outcomes into cases $B_1, \\dots, B_k$ that cover everything without overlapping. The event $E$ happens through one of these cases.',
          },
          {
            heading: 'Total probability',
            text: 'The overall probability is the average of the conditional probabilities, weighted by how likely each case is.',
            formula: 'P(E) = \\sum_i P(B_i)\\,P(E \\mid B_i)',
          },
          {
            heading: 'Common mistake',
            text: 'You must weight by each case’s probability. Averaging the rates without their weights is only correct when the cases are equally likely.',
          },
        ],
      },
      {
        id: 's3-total-probability-s2',
        type: 'problem',
        title: 'Two urns, equal chance',
        body: 'Two urns are equally likely. Urn 1 is 80% red; urn 2 is 20% red. You pick an urn at random, then draw a ball.',
        simulation: 'urnTree',
        simConfig: { urns: 2, w0: 1, p0: 0.8, w1: 1, p1: 0.2, trials: 2500 },
        question: 'What is P(red)? (decimal)',
        answer: totalProbability([
          { weight: 1, p: 0.8 },
          { weight: 1, p: 0.2 },
        ]),
        tolerance: 0.05,
        unit: 'probability',
        feedback: {
          correct: 'Right — ½(0.8) + ½(0.2) = 0.5.',
          incorrect: 'Average the two rates with equal weight: ½(0.8) + ½(0.2) = 0.5.',
        },
      },
      {
        id: 's3-total-probability-s3',
        type: 'problem',
        title: 'Unequal urns',
        body: 'Now urn 1 is chosen 70% of the time (90% red) and urn 2 30% of the time (20% red).',
        simulation: 'urnTree',
        simConfig: { urns: 2, w0: 7, p0: 0.9, w1: 3, p1: 0.2, trials: 2500 },
        question: 'What is P(red)? (decimal)',
        answer: totalProbability([
          { weight: 7, p: 0.9 },
          { weight: 3, p: 0.2 },
        ]),
        tolerance: 0.05,
        unit: 'probability',
        feedback: {
          correct: 'Exactly — 0.7(0.9) + 0.3(0.2) = 0.69.',
          incorrect: 'Weight by how often each urn is chosen: 0.7(0.9) + 0.3(0.2) = 0.69.',
        },
      },
      {
        id: 's3-total-probability-s4',
        type: 'problem',
        title: 'Three urns',
        body: 'Three equally likely urns are 90%, 50%, and 10% red.',
        simulation: 'urnTree',
        simConfig: { urns: 3, w0: 1, p0: 0.9, w1: 1, p1: 0.5, w2: 1, p2: 0.1, trials: 3000 },
        question: 'What is P(red)? (decimal)',
        answer: totalProbability([
          { weight: 1, p: 0.9 },
          { weight: 1, p: 0.5 },
          { weight: 1, p: 0.1 },
        ]),
        tolerance: 0.05,
        unit: 'probability',
        feedback: {
          correct: 'Right — the average of 0.9, 0.5, 0.1 is 0.5.',
          incorrect: 'Equal weights, so average the three rates: (0.9 + 0.5 + 0.1)/3 = 0.5.',
        },
      },
      {
        id: 's3-total-probability-s5',
        type: 'problem',
        title: 'Two machines',
        body: 'Machine A makes 60% of parts at a 2% defect rate; machine B makes 40% at a 5% defect rate.',
        simulation: 'urnTree',
        simConfig: { urns: 2, w0: 6, p0: 0.02, w1: 4, p1: 0.05, trials: 6000 },
        question: 'What is the overall probability a random part is defective? (decimal)',
        answer: totalProbability([
          { weight: 6, p: 0.02 },
          { weight: 4, p: 0.05 },
        ]),
        tolerance: 0.012,
        unit: 'probability',
        feedback: {
          correct: 'Exactly — 0.6(0.02) + 0.4(0.05) = 0.032.',
          incorrect: 'Weight each line’s defect rate: 0.6(0.02) + 0.4(0.05) = 0.032.',
        },
      },
      {
        id: 's3-total-probability-s6',
        type: 'problem',
        title: 'Weighted three',
        body: 'Three urns are chosen with weights 50%, 25%, 25% and are 60%, 20%, and 0% red.',
        simulation: 'urnTree',
        simConfig: { urns: 3, w0: 2, p0: 0.6, w1: 1, p1: 0.2, w2: 1, p2: 0, trials: 4000 },
        question: 'What is P(red)? (decimal)',
        answer: totalProbability([
          { weight: 2, p: 0.6 },
          { weight: 1, p: 0.2 },
          { weight: 1, p: 0 },
        ]),
        tolerance: 0.04,
        unit: 'probability',
        feedback: {
          correct: 'Right — 0.5(0.6) + 0.25(0.2) + 0.25(0) = 0.35.',
          incorrect: 'Weighted sum: 0.5(0.6) + 0.25(0.2) + 0.25(0) = 0.35.',
        },
      },
    ],
  },
  {
    id: 's3-bayes',
    index: 0,
    title: 'Bayes’ Theorem',
    concept: 'Updating on evidence',
    status: 'built',
    prerequisiteId: null,
    steps: [
      {
        id: 's3-bayes-s1',
        type: 'concept',
        title: 'When a positive isn’t the whole story',
        body: 'A test can be accurate yet most positives still be false — if the condition is rare. Reveal the population grid and watch how few of the flagged people actually have the condition.',
        simulation: 'bayesGrid',
        simConfig: { prior: 0.1, sens: 0.9, spec: 0.9, total: 100 },
        lecture: [
          {
            heading: 'Reversing the condition',
            text: 'Bayes’ theorem turns $P(+ \\mid D)$ (test accuracy) into $P(D \\mid +)$ (what you actually want) using the base rate.',
            formula: 'P(D \\mid +) = \\frac{P(+\\mid D)\\,P(D)}{P(+)}',
          },
          {
            heading: 'Natural frequencies',
            text: 'Out of a whole population, the positives are the true positives plus the false positives. The posterior is just the share of all positives that are real.',
            formula: 'P(D\\mid +) = \\frac{TP}{TP + FP}',
          },
          {
            heading: 'Common mistake — base-rate neglect',
            text: 'A rare condition makes false positives outnumber true ones even with a 90%-accurate test. Ignoring the base rate badly overestimates the posterior.',
          },
        ],
      },
      {
        id: 's3-bayes-s2',
        type: 'problem',
        title: 'A moderate base rate',
        body: 'A condition affects 30% of a group. The test is 90% sensitive and 90% specific.',
        simulation: 'bayesGrid',
        simConfig: { prior: 0.3, sens: 0.9, spec: 0.9, total: 100 },
        question: 'Given a positive test, what is P(condition)? (decimal)',
        answer: bayesPosterior(0.3, 0.9, 0.9),
        tolerance: 0.05,
        unit: 'probability',
        feedback: {
          correct: 'Right — TP = 0.27, FP = 0.07, so 0.27/0.34 ≈ 0.79.',
          incorrect: 'Compare true to false positives: 0.27 / (0.27 + 0.07) ≈ 0.79.',
        },
      },
      {
        id: 's3-bayes-s3',
        type: 'problem',
        title: 'A rare condition',
        body: 'Now the same 90%/90% test is used on a condition that affects only 1% of people.',
        simulation: 'bayesGrid',
        simConfig: { prior: 0.01, sens: 0.9, spec: 0.9, total: 1000 },
        question: 'Given a positive test, what is P(condition)? (decimal)',
        answer: bayesPosterior(0.01, 0.9, 0.9),
        tolerance: 0.03,
        unit: 'probability',
        feedback: {
          correct: 'Exactly — only ≈ 0.083. False positives swamp the few true ones.',
          incorrect: 'TP = 0.009 vs FP = 0.099, so 0.009/0.108 ≈ 0.083 — the base rate dominates.',
        },
      },
      {
        id: 's3-bayes-s4',
        type: 'problem',
        title: 'Sharper sensitivity',
        body: 'A condition affects 5%. A new test is 99% sensitive but still 90% specific.',
        simulation: 'bayesGrid',
        simConfig: { prior: 0.05, sens: 0.99, spec: 0.9, total: 1000 },
        question: 'Given a positive test, what is P(condition)? (decimal)',
        answer: bayesPosterior(0.05, 0.99, 0.9),
        tolerance: 0.05,
        unit: 'probability',
        feedback: {
          correct: 'Right — ≈ 0.34. Catching more true cases helps, but false positives still dominate.',
          incorrect: 'TP = 0.0495, FP = 0.095, so ≈ 0.34. Specificity, not sensitivity, is the bottleneck here.',
        },
      },
      {
        id: 's3-bayes-s5',
        type: 'problem',
        title: 'A second test',
        body: 'After one positive on the rare-condition (1%) test, the person’s probability is about 0.083. They take the same 90%/90% test again and it is positive again.',
        simulation: 'bayesGrid',
        simConfig: { prior: firstPositive, sens: 0.9, spec: 0.9, total: 1000 },
        question: 'What is P(condition) after the second positive? (decimal)',
        answer: bayesPosterior(firstPositive, 0.9, 0.9),
        tolerance: 0.06,
        unit: 'probability',
        feedback: {
          correct: 'Exactly — using 0.083 as the new prior gives ≈ 0.45. Evidence compounds.',
          incorrect: 'Feed the first posterior (0.083) back in as the prior: ≈ 0.45.',
        },
      },
    ],
  },
];
