import type { Lesson } from '../types/lesson';
import {
  geometricMean,
  geometricPmf,
  geometricTail,
  poissonPmf,
  hypergeometricPmf,
  measureRatio,
  expectedIndicatorSum,
} from '../lib/probability';

export const distributionsLessons: Lesson[] = [
  {
    id: 's5-geometric',
    index: 0,
    title: 'The Geometric Distribution',
    concept: 'Waiting for a first success',
    status: 'built',
    prerequisiteId: null,
    steps: [
      {
        id: 's5-geometric-s1',
        type: 'concept',
        title: 'How long until the first success?',
        body: 'Repeat a trial with success probability p until it works. The number of trials follows a geometric distribution — a histogram that decays by a factor of (1−p) each step.',
        simulation: 'waitingTime',
        simConfig: { p: 0.5, trials: 2000 },
        lecture: [
          {
            heading: 'Geometric PMF',
            text: 'To first succeed on trial $k$, you must fail $k-1$ times then succeed.',
            formula: 'P(X = k) = (1-p)^{k-1}\\,p',
          },
          {
            heading: 'Mean and tail',
            text: 'The expected wait is $1/p$, and the chance of taking more than $k$ trials is $(1-p)^k$.',
            formula: 'E[X] = \\tfrac{1}{p}, \\quad P(X > k) = (1-p)^k',
          },
          {
            heading: 'Memoryless',
            text: 'Past failures do not bring success closer: $P(X > s+t \\mid X > s) = P(X > t)$. The wait resets every trial.',
          },
        ],
      },
      {
        id: 's5-geometric-s2',
        type: 'problem',
        title: 'A fair coin',
        body: 'You flip a fair coin (p = 0.5) until it lands heads.',
        simulation: 'waitingTime',
        simConfig: { p: 0.5, trials: 4000 },
        question: 'What is the expected number of flips? (a number)',
        answer: geometricMean(0.5),
        tolerance: 0.3,
        unit: 'flips',
        feedback: {
          correct: 'Right — 1/p = 1/0.5 = 2.',
          incorrect: 'Mean of a geometric is 1/p = 2.',
        },
      },
      {
        id: 's5-geometric-s3',
        type: 'problem',
        title: 'A rarer success',
        body: 'A success has probability p = 0.2 each trial; you repeat until it occurs.',
        simulation: 'waitingTime',
        simConfig: { p: 0.2, trials: 5000 },
        question: 'What is the expected number of trials? (a number)',
        answer: geometricMean(0.2),
        tolerance: 0.6,
        unit: 'trials',
        feedback: {
          correct: 'Right — 1/0.2 = 5.',
          incorrect: 'Mean is 1/p = 1/0.2 = 5.',
        },
      },
      {
        id: 's5-geometric-s4',
        type: 'problem',
        title: 'Exactly on the third',
        body: 'A fair coin (p = 0.5) is flipped until heads.',
        simulation: 'waitingTime',
        simConfig: { p: 0.5, targetK: 3, readout: 1, trials: 4000 },
        question: 'What is the probability the first heads is on flip 3? (decimal)',
        answer: geometricPmf(3, 0.5),
        tolerance: 0.02,
        unit: 'probability',
        feedback: {
          correct: 'Right — (0.5)²(0.5) = 0.125: two tails then a head.',
          incorrect: 'P(X=3) = (1−p)²p = 0.5²·0.5 = 0.125.',
        },
      },
      {
        id: 's5-geometric-s5',
        type: 'problem',
        title: 'Still going',
        body: 'A fair coin (p = 0.5) is flipped until heads.',
        question: 'What is the probability it takes more than 4 flips? (decimal)',
        answer: geometricTail(4, 0.5),
        tolerance: 0.02,
        unit: 'probability',
        feedback: {
          correct: 'Right — (1−p)⁴ = 0.5⁴ = 0.0625: four tails in a row.',
          incorrect: 'P(X>4) = (1−p)⁴ = 0.0625.',
        },
      },
      {
        id: 's5-geometric-s6',
        type: 'problem',
        title: 'A long shot',
        body: 'A slot pays out with probability p = 0.1 each pull.',
        simulation: 'waitingTime',
        simConfig: { p: 0.1, trials: 6000 },
        question: 'What is the expected number of pulls until a payout? (a number)',
        answer: geometricMean(0.1),
        tolerance: 1,
        unit: 'pulls',
        feedback: {
          correct: 'Right — 1/0.1 = 10.',
          incorrect: 'Mean is 1/p = 10.',
        },
      },
    ],
  },
  {
    id: 's5-poisson',
    index: 0,
    title: 'The Poisson Distribution',
    concept: 'Counting rare events',
    status: 'built',
    prerequisiteId: null,
    steps: [
      {
        id: 's5-poisson-s1',
        type: 'concept',
        title: 'Events per interval',
        body: 'When events happen independently at a steady average rate λ, the count per interval is Poisson. Run intervals and watch the histogram match the Poisson curve, with mean λ.',
        simulation: 'poisson',
        simConfig: { lambda: 3, trials: 2000 },
        lecture: [
          {
            heading: 'Poisson PMF',
            text: 'For a mean rate $\\lambda$, the probability of exactly $k$ events is given by the Poisson formula.',
            formula: 'P(X = k) = \\frac{e^{-\\lambda}\\,\\lambda^{k}}{k!}',
          },
          {
            heading: 'Mean equals variance',
            text: 'A Poisson distribution has mean and variance both equal to $\\lambda$.',
            formula: 'E[X] = \\operatorname{Var}(X) = \\lambda',
          },
          {
            heading: 'Limit of the binomial',
            text: 'With many trials and a small success probability, a Binomial$(n,p)$ is approximately Poisson with $\\lambda = np$.',
          },
        ],
      },
      {
        id: 's5-poisson-s2',
        type: 'problem',
        title: 'Average rate',
        body: 'Calls arrive at a help desk at a mean rate of λ = 3 per minute.',
        simulation: 'poisson',
        simConfig: { lambda: 3, trials: 4000 },
        question: 'What is the expected number of calls per minute? (a number)',
        answer: 3,
        tolerance: 0.3,
        unit: 'calls',
        feedback: {
          correct: 'Right — the Poisson mean is λ = 3.',
          incorrect: 'The mean of a Poisson is λ, here 3.',
        },
      },
      {
        id: 's5-poisson-s3',
        type: 'problem',
        title: 'A quiet interval',
        body: 'Events occur at mean rate λ = 2 per interval.',
        simulation: 'poisson',
        simConfig: { lambda: 2, targetK: 0, readout: 1, trials: 3000 },
        question: 'What is the probability of 0 events in an interval? (decimal)',
        answer: poissonPmf(0, 2),
        tolerance: 0.02,
        unit: 'probability',
        feedback: {
          correct: 'Right — e⁻² ≈ 0.135.',
          incorrect: 'P(0) = e^{−λ} = e⁻² ≈ 0.135.',
        },
      },
      {
        id: 's5-poisson-s4',
        type: 'problem',
        title: 'Exactly three',
        body: 'Events occur at mean rate λ = 3 per interval.',
        simulation: 'poisson',
        simConfig: { lambda: 3, targetK: 3, readout: 1, trials: 3000 },
        question: 'What is the probability of exactly 3 events? (decimal)',
        answer: poissonPmf(3, 3),
        tolerance: 0.03,
        unit: 'probability',
        feedback: {
          correct: 'Right — e⁻³·3³/3! ≈ 0.224.',
          incorrect: 'P(3) = e⁻³·27/6 ≈ 0.224.',
        },
      },
      {
        id: 's5-poisson-s5',
        type: 'problem',
        title: 'Rare defects',
        body: 'A part is defective with probability 0.02, and you inspect 100 parts. Use the Poisson approximation with λ = np = 2.',
        simulation: 'poisson',
        simConfig: { lambda: 2, targetK: 0, readout: 1, trials: 3000 },
        question: 'What is the approximate probability of 0 defects? (decimal)',
        answer: poissonPmf(0, 2),
        tolerance: 0.02,
        unit: 'probability',
        feedback: {
          correct: 'Right — λ = 100(0.02) = 2, so P(0) ≈ e⁻² ≈ 0.135.',
          incorrect: 'Use λ = np = 2: P(0) ≈ e⁻² ≈ 0.135.',
        },
      },
    ],
  },
  {
    id: 's5-hypergeometric',
    index: 0,
    title: 'The Hypergeometric Distribution',
    concept: 'Successes without replacement',
    status: 'built',
    prerequisiteId: null,
    steps: [
      {
        id: 's5-hypergeometric-s1',
        type: 'concept',
        title: 'Drawing without replacement',
        body: 'When you draw a sample without replacement from a finite population, the number of successes is hypergeometric — each draw changes what is left. Run draws and watch the histogram of successes form.',
        simulation: 'hypergeometric',
        simConfig: { N: 52, K: 13, n: 5, trials: 3000 },
        lecture: [
          {
            heading: 'Hypergeometric PMF',
            text: 'From a population of $N$ with $K$ successes, drawing $n$ items gives exactly $k$ successes with a ratio of combinations.',
            formula: 'P(X=k) = \\frac{\\binom{K}{k}\\binom{N-K}{n-k}}{\\binom{N}{n}}',
          },
          {
            heading: 'Expected successes',
            text: 'By linearity, the expected number of successes is $n \\cdot K/N$ — the sample size times the population success rate.',
            formula: 'E[X] = n\\,\\frac{K}{N}',
          },
          {
            heading: 'Versus the binomial',
            text: 'With replacement the draws would be binomial. Without replacement the hypergeometric has slightly less spread; the two are close when the population is large.',
          },
        ],
      },
      {
        id: 's5-hypergeometric-s2',
        type: 'problem',
        title: 'Two aces',
        body: 'You draw 2 cards from a standard 52-card deck (4 aces).',
        simulation: 'hypergeometric',
        simConfig: { N: 52, K: 4, n: 2, targetK: 2, readout: 1, trials: 8000 },
        question: 'What is the probability both are aces? (decimal)',
        answer: hypergeometricPmf(52, 4, 2, 2),
        tolerance: 0.004,
        unit: 'probability',
        feedback: {
          correct: 'Right — C(4,2)/C(52,2) = 6/1326 ≈ 0.0045.',
          incorrect: 'P = C(4,2)·C(48,0)/C(52,2) = 6/1326 ≈ 0.0045.',
        },
      },
      {
        id: 's5-hypergeometric-s3',
        type: 'problem',
        title: 'Two hearts',
        body: 'You deal a 5-card hand from a 52-card deck (13 hearts).',
        simulation: 'hypergeometric',
        simConfig: { N: 52, K: 13, n: 5, targetK: 2, readout: 1, trials: 5000 },
        question: 'What is the probability of exactly 2 hearts? (decimal)',
        answer: hypergeometricPmf(52, 13, 5, 2),
        tolerance: 0.03,
        unit: 'probability',
        feedback: {
          correct: 'Right — C(13,2)·C(39,3)/C(52,5) ≈ 0.274.',
          incorrect: 'P = C(13,2)·C(39,3)/C(52,5) ≈ 0.274.',
        },
      },
      {
        id: 's5-hypergeometric-s4',
        type: 'problem',
        title: 'Red balls',
        body: 'An urn has 10 balls, 4 of them red. You draw 3 without replacement.',
        simulation: 'hypergeometric',
        simConfig: { N: 10, K: 4, n: 3, targetK: 2, readout: 1, trials: 4000 },
        question: 'What is the probability of exactly 2 red? (decimal)',
        answer: hypergeometricPmf(10, 4, 3, 2),
        tolerance: 0.03,
        unit: 'probability',
        feedback: {
          correct: 'Right — C(4,2)·C(6,1)/C(10,3) = 36/120 = 0.3.',
          incorrect: 'P = C(4,2)·C(6,1)/C(10,3) = 0.3 (a touch different from the binomial 0.288).',
        },
      },
      {
        id: 's5-hypergeometric-s5',
        type: 'problem',
        title: 'Expected successes',
        body: 'You draw 5 cards from 20 cards, 8 of which are "wild".',
        simulation: 'hypergeometric',
        simConfig: { N: 20, K: 8, n: 5, trials: 4000 },
        question: 'What is the expected number of wild cards drawn? (a number)',
        answer: expectedIndicatorSum(Array(5).fill(8 / 20)),
        tolerance: 0.15,
        unit: 'wild cards',
        feedback: {
          correct: 'Right — n·K/N = 5·(8/20) = 2.',
          incorrect: 'Expected successes = n·K/N = 5·8/20 = 2.',
        },
      },
    ],
  },
  {
    id: 's5-continuous-uniform',
    index: 0,
    title: 'The Continuous Uniform',
    concept: 'Probability as length',
    status: 'built',
    prerequisiteId: null,
    steps: [
      {
        id: 's5-continuous-uniform-s1',
        type: 'concept',
        title: 'Equally likely over a range',
        body: 'A continuous uniform spreads probability evenly over an interval. The chance of landing in a sub-range is just its length as a fraction of the whole. Drop points and watch the fraction in the shaded band settle on its length.',
        simulation: 'uniformLine',
        simConfig: { mode: 0, lo: 0.2, hi: 0.5, trials: 1200 },
        lecture: [
          {
            heading: 'Density and probability',
            text: 'On $[a,b]$ the density is constant at $1/(b-a)$, so the probability of a sub-interval is its length over the total length.',
            formula: 'P(c \\le X \\le d) = \\frac{d-c}{b-a}',
          },
          {
            heading: 'Mean',
            text: 'By symmetry the mean sits at the midpoint of the interval.',
            formula: 'E[X] = \\frac{a+b}{2}',
          },
          {
            heading: 'Common mistake',
            text: 'For a continuous variable the probability of any exact value is 0 — only ranges carry probability.',
          },
        ],
      },
      {
        id: 's5-continuous-uniform-s2',
        type: 'problem',
        title: 'A sub-interval',
        body: 'X is uniform on [0, 1].',
        simulation: 'uniformLine',
        simConfig: { mode: 0, lo: 0, hi: 0.3, trials: 1500 },
        question: 'What is P(0 ≤ X ≤ 0.3)? (decimal)',
        answer: measureRatio(0.3, 1),
        tolerance: 0.04,
        unit: 'probability',
        feedback: {
          correct: 'Right — length 0.3 over length 1 is 0.3.',
          incorrect: 'It is the sub-length over the total: 0.3/1 = 0.3.',
        },
      },
      {
        id: 's5-continuous-uniform-s3',
        type: 'problem',
        title: 'A middle band',
        body: 'X is uniform on [0, 1].',
        simulation: 'uniformLine',
        simConfig: { mode: 0, lo: 0.2, hi: 0.5, trials: 1500 },
        question: 'What is P(0.2 ≤ X ≤ 0.5)? (decimal)',
        answer: measureRatio(0.5 - 0.2, 1),
        tolerance: 0.04,
        unit: 'probability',
        feedback: {
          correct: 'Right — the band has length 0.3.',
          incorrect: 'Length of [0.2, 0.5] is 0.3, over total 1.',
        },
      },
      {
        id: 's5-continuous-uniform-s4',
        type: 'problem',
        title: 'Two bands',
        body: 'X is uniform on [0, 1].',
        simulation: 'uniformLine',
        simConfig: { mode: 1, lo: 0.25, hi: 0.75, trials: 1500 },
        question: 'What is P(X ≤ 0.25 or X ≥ 0.75)? (decimal)',
        answer: measureRatio(0.25 + 0.25, 1),
        tolerance: 0.04,
        unit: 'probability',
        feedback: {
          correct: 'Right — two lengths of 0.25 sum to 0.5.',
          incorrect: 'Add the two sub-lengths: 0.25 + 0.25 = 0.5.',
        },
      },
      {
        id: 's5-continuous-uniform-s5',
        type: 'problem',
        title: 'Conditional length',
        body: 'X is uniform on [0, 1]. You are told X ≤ 0.6.',
        question: 'Given that, what is P(X ≤ 0.2)? (decimal)',
        answer: measureRatio(0.2, 0.6),
        tolerance: 0.03,
        unit: 'probability',
        feedback: {
          correct: 'Right — restrict to [0, 0.6]: 0.2/0.6 ≈ 0.333.',
          incorrect: 'Condition on [0, 0.6]: P = 0.2/0.6 ≈ 0.333.',
        },
      },
      {
        id: 's5-continuous-uniform-s6',
        type: 'problem',
        title: 'The mean',
        body: 'X is uniform on the interval [2, 8].',
        question: 'What is the mean of X? (a number)',
        answer: (2 + 8) / 2,
        tolerance: 0.2,
        unit: 'value',
        feedback: {
          correct: 'Right — the mean of a uniform is the midpoint: (2 + 8)/2 = 5.',
          incorrect: 'The uniform mean is the midpoint of the interval: (2 + 8)/2 = 5.',
        },
      },
    ],
  },
];
