import type { Lesson } from '../types/lesson';
import {
  buffonProbability,
  bertrandLongerThanSide,
  uniformOrderMean,
  measureRatio,
  expectedAbsDifferenceUniform,
  brokenStickTriangleProbability,
} from '../lib/probability';

export const geometricLessons: Lesson[] = [
  {
    id: 's8-area-ratio',
    index: 0,
    title: 'Probability as Area',
    concept: 'Chance from geometry',
    status: 'built',
    prerequisiteId: null,
    steps: [
      {
        id: 's8-area-ratio-s1',
        type: 'concept',
        title: 'Throwing darts',
        body: 'For a uniformly random point, probability is just area. Throw darts at the unit square and the fraction landing in a region equals that region’s area.',
        simulation: 'dartThrow',
        simConfig: { shape: 0, size: 0.5, trials: 1500 },
        lecture: [
          {
            heading: 'Probability is a ratio of measures',
            text: 'For a uniform point, the probability of a region equals its measure (length, area, or volume) over the total.',
            formula: 'P(\\text{region}) = \\frac{\\text{area of region}}{\\text{total area}}',
          },
          {
            heading: 'Reduce to geometry',
            text: 'Many probability questions become "what fraction of the space qualifies?" — a pure area calculation.',
          },
          {
            heading: 'Common mistake',
            text: 'This only works when points are uniform. Non-uniform densities weight regions differently.',
          },
        ],
      },
      {
        id: 's8-area-ratio-s2',
        type: 'problem',
        title: 'Inscribed circle',
        body: 'A circle of radius 0.5 sits inside the unit square; a dart lands uniformly.',
        simulation: 'dartThrow',
        simConfig: { shape: 0, size: 0.5, trials: 3000 },
        question: 'What is the probability it lands in the circle? (decimal)',
        answer: Math.PI * 0.5 * 0.5,
        tolerance: 0.03,
        unit: 'probability',
        feedback: {
          correct: 'Right — area πr² = π(0.5)² = π/4 ≈ 0.785.',
          incorrect: 'It is the circle’s area: π(0.5)² = π/4 ≈ 0.785.',
        },
      },
      {
        id: 's8-area-ratio-s3',
        type: 'problem',
        title: 'A centered square',
        body: 'A square of side 0.6 is centered in the unit square.',
        simulation: 'dartThrow',
        simConfig: { shape: 1, size: 0.6, trials: 3000 },
        question: 'What is the probability the dart lands in it? (decimal)',
        answer: 0.6 * 0.6,
        tolerance: 0.03,
        unit: 'probability',
        feedback: {
          correct: 'Right — 0.6² = 0.36.',
          incorrect: 'Area of the sub-square: 0.6² = 0.36.',
        },
      },
      {
        id: 's8-area-ratio-s4',
        type: 'problem',
        title: 'A corner triangle',
        body: 'The region is the triangle where x + y ≤ 1 (the lower-left half).',
        simulation: 'dartThrow',
        simConfig: { shape: 2, size: 1, trials: 3000 },
        question: 'What is the probability the dart lands in it? (decimal)',
        answer: 0.5,
        tolerance: 0.03,
        unit: 'probability',
        feedback: {
          correct: 'Right — the triangle is exactly half the square: 0.5.',
          incorrect: 'x + y ≤ 1 is half the unit square: area 0.5.',
        },
      },
      {
        id: 's8-area-ratio-s5',
        type: 'problem',
        title: 'A smaller circle',
        body: 'Now a circle of radius 0.3 is centered in the unit square.',
        simulation: 'dartThrow',
        simConfig: { shape: 0, size: 0.3, trials: 4000 },
        question: 'What is the probability the dart lands in it? (decimal)',
        answer: Math.PI * 0.3 * 0.3,
        tolerance: 0.03,
        unit: 'probability',
        feedback: {
          correct: 'Right — π(0.3)² ≈ 0.283.',
          incorrect: 'Area = π(0.3)² ≈ 0.283.',
        },
      },
      {
        id: 's8-area-ratio-s6',
        type: 'problem',
        title: 'A small square',
        body: 'A square of side 0.4 is centered in the unit square.',
        simulation: 'dartThrow',
        simConfig: { shape: 1, size: 0.4, trials: 4000 },
        question: 'What is the probability the dart lands in it? (decimal)',
        answer: 0.4 * 0.4,
        tolerance: 0.03,
        unit: 'probability',
        feedback: {
          correct: 'Right — 0.4² = 0.16.',
          incorrect: 'Area = 0.4² = 0.16.',
        },
      },
    ],
  },
  {
    id: 's8-buffon',
    index: 0,
    title: 'Buffon’s Needle',
    concept: 'Estimating π by dropping needles',
    status: 'built',
    prerequisiteId: null,
    steps: [
      {
        id: 's8-buffon-s1',
        type: 'concept',
        title: 'Needles across the lines',
        body: 'Drop a needle of length L on a floor ruled with lines spaced d = 1 apart. The chance it crosses a line is 2L/(πd) — drop many and π appears.',
        simulation: 'buffon',
        simConfig: { L: 1, trials: 2000 },
        lecture: [
          {
            heading: 'Crossing probability',
            text: 'For a needle no longer than the line spacing, the crossing probability is a clean formula involving π.',
            formula: 'P(\\text{cross}) = \\frac{2L}{\\pi d}',
          },
          {
            heading: 'An estimate of π',
            text: 'Rearranging, π ≈ 2L / (d · crossing fraction). Many drops give a Monte-Carlo estimate of π.',
          },
          {
            heading: 'Common mistake',
            text: 'The simple formula assumes L ≤ d. Longer needles can cross multiple lines and need a different formula.',
          },
        ],
      },
      {
        id: 's8-buffon-s2',
        type: 'problem',
        title: 'Needle as long as the gap',
        body: 'L = 1 and d = 1.',
        simulation: 'buffon',
        simConfig: { L: 1, trials: 4000 },
        question: 'What is the probability of crossing a line? (decimal)',
        answer: buffonProbability(1, 1),
        tolerance: 0.03,
        unit: 'probability',
        feedback: {
          correct: 'Right — 2/π ≈ 0.637.',
          incorrect: 'P = 2L/(πd) = 2/π ≈ 0.637.',
        },
      },
      {
        id: 's8-buffon-s3',
        type: 'problem',
        title: 'Half-length needle',
        body: 'L = 0.5, d = 1.',
        simulation: 'buffon',
        simConfig: { L: 0.5, trials: 5000 },
        question: 'What is the crossing probability? (decimal)',
        answer: buffonProbability(0.5, 1),
        tolerance: 0.03,
        unit: 'probability',
        feedback: {
          correct: 'Right — 1/π ≈ 0.318.',
          incorrect: 'P = 2(0.5)/π = 1/π ≈ 0.318.',
        },
      },
      {
        id: 's8-buffon-s4',
        type: 'problem',
        title: 'A longer needle',
        body: 'L = 0.8, d = 1.',
        simulation: 'buffon',
        simConfig: { L: 0.8, trials: 5000 },
        question: 'What is the crossing probability? (decimal)',
        answer: buffonProbability(0.8, 1),
        tolerance: 0.03,
        unit: 'probability',
        feedback: {
          correct: 'Right — 1.6/π ≈ 0.509.',
          incorrect: 'P = 2(0.8)/π ≈ 0.509.',
        },
      },
      {
        id: 's8-buffon-s5',
        type: 'problem',
        title: 'A short needle',
        body: 'L = 0.25, d = 1.',
        simulation: 'buffon',
        simConfig: { L: 0.25, trials: 8000 },
        question: 'What is the crossing probability? (decimal)',
        answer: buffonProbability(0.25, 1),
        tolerance: 0.02,
        unit: 'probability',
        feedback: {
          correct: 'Right — 0.5/π ≈ 0.159.',
          incorrect: 'P = 2(0.25)/π ≈ 0.159.',
        },
      },
    ],
  },
  {
    id: 's8-bertrand',
    index: 0,
    title: 'The Bertrand Paradox',
    concept: 'What does “random” mean?',
    status: 'built',
    prerequisiteId: null,
    steps: [
      {
        id: 's8-bertrand-s1',
        type: 'concept',
        title: 'Three answers to one question',
        body: 'How likely is a “random” chord to be longer than the inscribed triangle’s side? It depends on how you randomize — three natural methods give three different answers.',
        simulation: 'randomChord',
        simConfig: { method: 0, trials: 1500 },
        lecture: [
          {
            heading: 'A famous ambiguity',
            text: 'Random endpoints, a random radius, and a random midpoint each define "random chord" differently — and each yields a different probability.',
            formula: '\\tfrac13,\\quad \\tfrac12,\\quad \\tfrac14',
          },
          {
            heading: 'The lesson',
            text: 'Probability requires a precise sampling mechanism. "At random" is not well defined until you say exactly how.',
          },
        ],
      },
      {
        id: 's8-bertrand-s2',
        type: 'problem',
        title: 'Random endpoints',
        body: 'Pick two independent uniform points on the circle and connect them.',
        simulation: 'randomChord',
        simConfig: { method: 0, trials: 3000 },
        question: 'What fraction of chords are longer than the triangle’s side? (decimal)',
        answer: bertrandLongerThanSide(0),
        tolerance: 0.04,
        unit: 'fraction',
        feedback: {
          correct: 'Right — this method gives 1/3.',
          incorrect: 'Random endpoints give 1/3 (the arc must exceed 120°).',
        },
      },
      {
        id: 's8-bertrand-s3',
        type: 'problem',
        title: 'Random radius',
        body: 'Pick a random radius, then a random point along it for the chord’s midpoint.',
        simulation: 'randomChord',
        simConfig: { method: 1, trials: 3000 },
        question: 'What fraction are longer than the side now? (decimal)',
        answer: bertrandLongerThanSide(1),
        tolerance: 0.04,
        unit: 'fraction',
        feedback: {
          correct: 'Right — this method gives 1/2 (midpoint within half the radius).',
          incorrect: 'Random radius gives 1/2.',
        },
      },
      {
        id: 's8-bertrand-s4',
        type: 'problem',
        title: 'Random midpoint',
        body: 'Pick the chord’s midpoint uniformly over the disk.',
        simulation: 'randomChord',
        simConfig: { method: 2, trials: 3000 },
        question: 'What fraction are longer than the side? (decimal)',
        answer: bertrandLongerThanSide(2),
        tolerance: 0.04,
        unit: 'fraction',
        feedback: {
          correct: 'Right — this method gives 1/4 (midpoint inside the half-radius disk).',
          incorrect: 'Random midpoint gives 1/4 — an area ratio of (1/2)².',
        },
      },
      {
        id: 's8-bertrand-s5',
        type: 'problem',
        title: 'A point near the center',
        body: 'Pick a point uniformly in a disk. (This is the area behind method 3.)',
        question: 'What is the probability it lies within half the radius of the center? (decimal)',
        answer: measureRatio(0.25, 1),
        tolerance: 0.03,
        unit: 'probability',
        feedback: {
          correct: 'Right — area ratio (1/2)² = 0.25.',
          incorrect: 'The inner disk has 1/4 the area: (1/2)² = 0.25.',
        },
      },
    ],
  },
  {
    id: 's8-order-stats',
    index: 0,
    title: 'Order Statistics',
    concept: 'Min, max, and distances',
    status: 'built',
    prerequisiteId: null,
    steps: [
      {
        id: 's8-order-stats-s1',
        type: 'concept',
        title: 'The extremes of a sample',
        body: 'Sample several uniform points and the smallest and largest behave predictably. The r-th smallest of n averages r/(n+1). Sample and watch the maximum’s mean settle.',
        simulation: 'orderStats',
        simConfig: { n: 5, r: 5, trials: 2000 },
        lecture: [
          {
            heading: 'Order statistics',
            text: 'Sort n uniform draws; the r-th value has expected value r/(n+1). The max is n/(n+1), the min is 1/(n+1).',
            formula: 'E[X_{(r)}] = \\frac{r}{n+1}',
          },
          {
            heading: 'Distances',
            text: 'Two independent uniform points are on average 1/3 apart, and a stick broken at two random points forms a triangle 1/4 of the time.',
          },
          {
            heading: 'Common mistake',
            text: 'Extremes do not behave like the mean. The maximum drifts toward 1 as n grows, not toward the average 1/2.',
          },
        ],
      },
      {
        id: 's8-order-stats-s2',
        type: 'problem',
        title: 'The maximum of five',
        body: 'You sample 5 uniform points on [0, 1].',
        simulation: 'orderStats',
        simConfig: { n: 5, r: 5, trials: 4000 },
        question: 'What is the expected value of the maximum? (decimal)',
        answer: uniformOrderMean(5, 5),
        tolerance: 0.03,
        unit: 'value',
        feedback: {
          correct: 'Right — n/(n+1) = 5/6 ≈ 0.833.',
          incorrect: 'E[max] = n/(n+1) = 5/6 ≈ 0.833.',
        },
      },
      {
        id: 's8-order-stats-s3',
        type: 'problem',
        title: 'The minimum of five',
        body: 'Same 5 uniform points.',
        simulation: 'orderStats',
        simConfig: { n: 5, r: 1, trials: 4000 },
        question: 'What is the expected value of the minimum? (decimal)',
        answer: uniformOrderMean(5, 1),
        tolerance: 0.03,
        unit: 'value',
        feedback: {
          correct: 'Right — 1/(n+1) = 1/6 ≈ 0.167.',
          incorrect: 'E[min] = 1/(n+1) = 1/6 ≈ 0.167.',
        },
      },
      {
        id: 's8-order-stats-s4',
        type: 'problem',
        title: 'More samples push the max up',
        body: 'Now you sample 10 uniform points.',
        simulation: 'orderStats',
        simConfig: { n: 10, r: 10, trials: 4000 },
        question: 'What is the expected maximum of 10? (decimal)',
        answer: uniformOrderMean(10, 10),
        tolerance: 0.03,
        unit: 'value',
        feedback: {
          correct: 'Right — 10/11 ≈ 0.909, closer to 1 than with 5.',
          incorrect: 'E[max] = 10/11 ≈ 0.909.',
        },
      },
      {
        id: 's8-order-stats-s5',
        type: 'problem',
        title: 'Distance between two points',
        body: 'Two points are dropped independently and uniformly on [0, 1].',
        question: 'What is the expected distance between them? (decimal)',
        answer: expectedAbsDifferenceUniform(),
        tolerance: 0.03,
        unit: 'distance',
        feedback: {
          correct: 'Right — E|U − V| = 1/3.',
          incorrect: 'The expected gap between two uniform points is 1/3.',
        },
      },
      {
        id: 's8-order-stats-s6',
        type: 'problem',
        title: 'The broken stick',
        body: 'A unit stick is broken at two independent uniform points into three pieces.',
        question: 'What is the probability the three pieces form a triangle? (decimal)',
        answer: brokenStickTriangleProbability(),
        tolerance: 0.03,
        unit: 'probability',
        feedback: {
          correct: 'Right — exactly 1/4. No piece may exceed half the length.',
          incorrect: 'The classic broken-stick answer is 1/4.',
        },
      },
    ],
  },
];
