import type { Lesson } from '../types/lesson';
import {
  longRunFrequency,
  mostLikelyDiceSumProbability,
  diceSumDistribution,
  binomialPmf,
  galtonCenterFraction,
  birthdayProb,
  montyHallSwitchWin,
} from '../lib/probability';
import { wheelConfig, wheelEV } from './simData';

const dice = diceSumDistribution();

const dieWheel = [1, 2, 3, 4, 5, 6].map((v) => ({ value: v, p: 1 / 6 }));
const lotteryWheel = [
  { value: 0, p: 0.9 },
  { value: 100, p: 0.1 },
];
const prizeWheel = [
  { value: 1, p: 0.5 },
  { value: 5, p: 0.3 },
  { value: 10, p: 0.2 },
];

/**
 * The course. Lessons 1-3 are fully built and playable. Lessons 4-7 ship as
 * `coming-soon` so the full intended depth is visible without claiming it works.
 * Every numeric `answer` is computed by the owned probability functions above.
 */
export const lessons: Lesson[] = [
  {
    id: 'l1-coin-flip',
    index: 1,
    title: 'What is Probability?',
    concept: 'Long-run frequency',
    status: 'built',
    prerequisiteId: null,
    steps: [
      {
        id: 'l1-s1',
        type: 'concept',
        title: 'Flip until it clicks',
        body: 'Probability is what happens in the long run. Drag the slider to flip a coin many times and watch the fraction of heads settle toward one half. A few flips are wild and lopsided; thousands of flips are remarkably steady.',
        simulation: 'coinFlip',
        simConfig: { flips: 100, p: 0.5 },
      },
      {
        id: 'l1-s2',
        type: 'problem',
        title: 'Predict the long run',
        body: 'You are about to flip a fair coin 1000 times.',
        simulation: 'coinFlip',
        simConfig: { flips: 1000, p: 0.5 },
        question: 'What fraction of the 1000 flips will come up heads? (enter a decimal, e.g. 0.5)',
        answer: longRunFrequency(0.5),
        tolerance: 0.05,
        unit: 'fraction',
        feedback: {
          correct: 'Exactly. A fair coin has no memory and no preference — over many flips the fraction of heads converges to one half.',
          incorrect: 'Close, but a fair coin converges to 0.5. Each flip is 50/50, so over 1000 flips roughly half land heads.',
        },
      },
      {
        id: 'l1-s3',
        type: 'problem',
        title: 'When the coin is bent',
        body: 'Now the coin is biased: it lands heads 75% of the time on each flip.',
        simulation: 'coinFlip',
        simConfig: { flips: 1000, p: 0.75 },
        question: 'Over 1000 flips of this biased coin, what fraction will be heads?',
        answer: longRunFrequency(0.75),
        tolerance: 0.05,
        unit: 'fraction',
        feedback: {
          correct: 'Right. Long-run frequency converges to the true probability of the process — here that is 0.75.',
          incorrect: 'The frequency converges to the coin’s actual bias. If every flip is 75% heads, about 0.75 of all flips are heads.',
        },
      },
      {
        id: 'l1-s4',
        type: 'problem',
        title: 'The gambler’s trap',
        body: 'You flip a fair coin 10 times and happen to get 7 heads.',
        simulation: 'coinFlip',
        simConfig: { flips: 1000, p: 0.5 },
        question: 'Continuing with the same fair coin, what fraction of the next 1000 flips do you predict are heads?',
        answer: longRunFrequency(0.5),
        tolerance: 0.05,
        unit: 'fraction',
        feedback: {
          correct: 'Yes — the coin has no memory. A streak of heads does not make tails “due.” The long run is still 0.5.',
          incorrect: 'A fair coin does not correct for past streaks. The next 1000 flips still converge to 0.5, regardless of what just happened.',
        },
      },
    ],
  },
  {
    id: 'l2-dice-roll',
    index: 2,
    title: 'Independent Events',
    concept: 'Combining independent outcomes',
    status: 'built',
    prerequisiteId: 'l1-coin-flip',
    steps: [
      {
        id: 'l2-s1',
        type: 'concept',
        title: 'Two dice, many sums',
        body: 'Each die is independent — one roll never affects the other. But when you add two dice, the sums are not equally likely. Roll many times and watch the histogram of sums build into a triangle.',
        simulation: 'diceRoll',
        simConfig: { rolls: 100 },
      },
      {
        id: 'l2-s2',
        type: 'problem',
        title: 'The peak of the triangle',
        body: 'There are 36 equally likely ways two dice can land.',
        simulation: 'diceRoll',
        simConfig: { rolls: 2000 },
        question: 'Which sum is the single most likely? (enter the number)',
        answer: 7,
        tolerance: 0.5,
        unit: 'sum',
        feedback: {
          correct: 'Right — 7 has the most combinations (1+6, 2+5, 3+4, and their reverses): six ways out of 36.',
          incorrect: 'The most likely sum is 7. It can be made six different ways, more than any other sum.',
        },
      },
      {
        id: 'l2-s3',
        type: 'problem',
        title: 'How likely is seven?',
        body: 'Seven can be rolled six ways out of 36 total outcomes.',
        simulation: 'diceRoll',
        simConfig: { rolls: 2000 },
        question: 'What is the probability of rolling a sum of 7? (decimal)',
        answer: mostLikelyDiceSumProbability(),
        tolerance: 0.02,
        unit: 'probability',
        feedback: {
          correct: 'Exactly — 6 favorable outcomes out of 36 is 1/6 ≈ 0.167.',
          incorrect: 'There are 6 ways to make 7 out of 36 outcomes: 6/36 = 1/6 ≈ 0.167.',
        },
      },
      {
        id: 'l2-s4',
        type: 'problem',
        title: 'Snake eyes',
        body: 'A sum of 2 requires both dice to show 1.',
        simulation: 'diceRoll',
        simConfig: { rolls: 2000 },
        question: 'What is the probability of rolling a sum of 2? (decimal)',
        answer: dice[2],
        tolerance: 0.02,
        unit: 'probability',
        feedback: {
          correct: 'Right — only one outcome (1,1) out of 36, so 1/36 ≈ 0.028. Extremes are rare.',
          incorrect: 'Only (1,1) makes a 2 — one way out of 36, so 1/36 ≈ 0.028.',
        },
      },
    ],
  },
  {
    id: 'l3-galton-board',
    index: 3,
    title: 'The Galton Board',
    concept: 'How the bell curve emerges',
    status: 'built',
    prerequisiteId: 'l2-dice-roll',
    steps: [
      {
        id: 'l3-s1',
        type: 'concept',
        title: 'Build a bell curve from chance',
        body: 'Each ball bounces left or right at every peg — a coin flip at each row. Independent random choices, stacked together, pile up into a bell-shaped curve. Drop some balls and watch the bins fill.',
        simulation: 'galtonBoard',
        simConfig: { rows: 12, balls: 200 },
      },
      {
        id: 'l3-s2',
        type: 'problem',
        title: 'Where do the balls pile up?',
        body: 'This board has 12 rows, so balls collect in 13 bins. Most pile up in the middle.',
        simulation: 'galtonBoard',
        simConfig: { rows: 12, balls: 1000 },
        question: 'What fraction of balls land in the three central bins? (decimal)',
        answer: galtonCenterFraction(12, 3),
        tolerance: 0.06,
        unit: 'fraction',
        feedback: {
          correct: 'Yes — the center dominates. Around 61% of balls land in just the three middle bins.',
          incorrect: 'The three central bins hold the bulk of the balls — about 0.61 of them. The middle is by far the most likely place to land.',
        },
      },
      {
        id: 'l3-s3',
        type: 'problem',
        title: 'The single peak',
        body: 'The exact center bin corresponds to an equal number of left and right bounces.',
        simulation: 'galtonBoard',
        simConfig: { rows: 12, balls: 1000 },
        question: 'What fraction of balls land in the one exact-center bin? (decimal)',
        answer: binomialPmf(12, 6, 0.5),
        tolerance: 0.03,
        unit: 'fraction',
        feedback: {
          correct: 'Right — about 0.23. Even the single most likely bin only gets roughly a quarter of the balls.',
          incorrect: 'The center bin gets about 0.23 of the balls — the most of any single bin, but still under a quarter.',
        },
      },
      {
        id: 'l3-s4',
        type: 'problem',
        title: 'The lonely edges',
        body: 'The two outermost bins require a ball to bounce the same direction at every single peg.',
        simulation: 'galtonBoard',
        simConfig: { rows: 12, balls: 1000 },
        question: 'What fraction of balls land in the two outermost bins combined? (decimal)',
        answer: binomialPmf(12, 0, 0.5) + binomialPmf(12, 12, 0.5),
        tolerance: 0.02,
        unit: 'fraction',
        feedback: {
          correct: 'Exactly — almost none. Bouncing the same way 12 times in a row is vanishingly rare (about 0.0005).',
          incorrect: 'The edges are nearly empty — about 0.0005. Hitting all-left or all-right twelve times running almost never happens.',
        },
      },
    ],
  },
  {
    id: 'l4-birthday',
    index: 4,
    title: 'The Birthday Problem',
    concept: 'Counterintuitive collisions',
    status: 'built',
    prerequisiteId: 'l3-galton-board',
    steps: [
      {
        id: 'l4-s1',
        type: 'concept',
        title: 'A surprising collision',
        body: 'How many people need to be in a room before two of them probably share a birthday? The answer is shockingly small. Drag the slider and simulate rooms — the curve climbs much faster than intuition suggests, because every new person creates many new pairs that could match.',
        simulation: 'birthday',
        simConfig: { people: 23 },
      },
      {
        id: 'l4-s2',
        type: 'problem',
        title: 'Twenty-three strangers',
        body: 'A room holds 23 people, each with a random birthday.',
        simulation: 'birthday',
        simConfig: { people: 23, trials: 3000 },
        question: 'What is the probability that at least two share a birthday? (decimal)',
        answer: birthdayProb(23),
        tolerance: 0.08,
        unit: 'probability',
        feedback: {
          correct: 'Yes — just past 23 people it crosses 50%. With 253 possible pairs, a match becomes more likely than not.',
          incorrect: 'It is about 0.51 — better than a coin flip. Counting pairs (not people) is the key: 23 people make 253 pairs.',
        },
      },
      {
        id: 'l4-s3',
        type: 'problem',
        title: 'A smaller gathering',
        body: 'Now only 10 people are in the room.',
        simulation: 'birthday',
        simConfig: { people: 10, trials: 3000 },
        question: 'What is the probability that two of the 10 share a birthday? (decimal)',
        answer: birthdayProb(10),
        tolerance: 0.06,
        unit: 'probability',
        feedback: {
          correct: 'Right — about 0.12. Fewer people means far fewer pairs, so a match is still fairly unlikely.',
          incorrect: 'It is about 0.12. Ten people form only 45 pairs, so a shared birthday is still uncommon.',
        },
      },
      {
        id: 'l4-s4',
        type: 'problem',
        title: 'A full classroom',
        body: 'A classroom contains 40 students.',
        simulation: 'birthday',
        simConfig: { people: 40, trials: 3000 },
        question: 'What is the probability that two students share a birthday? (decimal)',
        answer: birthdayProb(40),
        tolerance: 0.06,
        unit: 'probability',
        feedback: {
          correct: 'Exactly — nearly 0.89. By 40 people a shared birthday is almost guaranteed.',
          incorrect: 'It is about 0.89 — nearly certain. The pair count explodes: 40 people make 780 pairs.',
        },
      },
    ],
  },
  {
    id: 'l5-expected-value',
    index: 5,
    title: 'Expected Value',
    concept: 'Weighted average of outcomes',
    status: 'built',
    prerequisiteId: 'l4-birthday',
    steps: [
      {
        id: 'l5-s1',
        type: 'concept',
        title: 'The long-run average',
        body: 'Expected value is the average payout you would get per try if you repeated a game forever. It is each outcome weighted by its probability. Spin the prize wheel many times and watch the running average settle on a single number — that number is the expected value.',
        simulation: 'expectedValue',
        simConfig: wheelConfig(prizeWheel),
      },
      {
        id: 'l5-s2',
        type: 'problem',
        title: 'The prize wheel',
        body: 'This wheel pays $1 half the time, $5 with probability 0.3, and $10 with probability 0.2.',
        simulation: 'expectedValue',
        simConfig: wheelConfig(prizeWheel),
        question: 'What is the expected payout of a single spin? (dollars)',
        answer: wheelEV(prizeWheel),
        tolerance: 0.4,
        unit: 'dollars',
        feedback: {
          correct: 'Right — 1(0.5) + 5(0.3) + 10(0.2) = $4.00. The average lands between the outcomes, weighted by their chances.',
          incorrect: 'Weight each prize by its probability: 1(0.5) + 5(0.3) + 10(0.2) = $4.00.',
        },
      },
      {
        id: 'l5-s3',
        type: 'problem',
        title: 'A roll of the die',
        body: 'A game pays you, in dollars, whatever a fair six-sided die shows.',
        simulation: 'expectedValue',
        simConfig: wheelConfig(dieWheel),
        question: 'What is the expected payout of one roll? (dollars)',
        answer: wheelEV(dieWheel),
        tolerance: 0.4,
        unit: 'dollars',
        feedback: {
          correct: 'Yes — (1+2+3+4+5+6)/6 = 3.5. Expected value need not be a value you can actually roll.',
          incorrect: 'Average the six equally likely faces: (1+2+3+4+5+6)/6 = $3.50.',
        },
      },
      {
        id: 'l5-s4',
        type: 'problem',
        title: 'The long-shot lottery',
        body: 'A ticket pays $100 with probability 0.1, and nothing otherwise.',
        simulation: 'expectedValue',
        simConfig: wheelConfig(lotteryWheel),
        question: 'What is the expected value of one ticket? (dollars)',
        answer: wheelEV(lotteryWheel),
        tolerance: 1,
        unit: 'dollars',
        feedback: {
          correct: 'Right — 100(0.1) + 0(0.9) = $10. A rare big prize still has a modest expected value.',
          incorrect: 'A 0.1 chance at $100 is worth 100 × 0.1 = $10 on average.',
        },
      },
    ],
  },
  {
    id: 'l6-conditional',
    index: 6,
    title: 'Conditional Probability',
    concept: 'Updating on new information',
    status: 'built',
    prerequisiteId: 'l5-expected-value',
    steps: [
      {
        id: 'l6-s1',
        type: 'concept',
        title: 'Information changes the odds',
        body: 'A conditional probability is the chance of an event given that something else has already happened. Drawing cards without replacement is the cleanest example: once a card is gone, the deck — and every probability — changes. Deal many times and watch the fractions settle.',
        simulation: 'conditional',
        simConfig: { metric: 0, scaleMax: 0.15 },
      },
      {
        id: 'l6-s2',
        type: 'problem',
        title: 'The first card',
        body: 'You draw one card from a freshly shuffled 52-card deck.',
        simulation: 'conditional',
        simConfig: { metric: 0, scaleMax: 0.15, trials: 6000 },
        question: 'What is the probability it is an ace? (decimal)',
        answer: 4 / 52,
        tolerance: 0.02,
        unit: 'probability',
        feedback: {
          correct: 'Right — 4 aces out of 52 cards is 1/13 ≈ 0.077.',
          incorrect: 'There are 4 aces in 52 cards: 4/52 = 1/13 ≈ 0.077.',
        },
      },
      {
        id: 'l6-s3',
        type: 'problem',
        title: 'Given the first was an ace',
        body: 'Your first card was an ace and you set it aside. Now 51 cards remain, 3 of them aces.',
        simulation: 'conditional',
        simConfig: { metric: 2, scaleMax: 0.15, trials: 8000 },
        question: 'What is the probability the next card is also an ace? (decimal)',
        answer: 3 / 51,
        tolerance: 0.02,
        unit: 'probability',
        feedback: {
          correct: 'Yes — conditioning on the first ace leaves 3 aces in 51 cards: 3/51 ≈ 0.059.',
          incorrect: 'After removing one ace, 3 aces remain among 51 cards: 3/51 ≈ 0.059.',
        },
      },
      {
        id: 'l6-s4',
        type: 'problem',
        title: 'Both at once',
        body: 'You draw two cards from a full deck. The two events combine: ace first, then ace again.',
        simulation: 'conditional',
        simConfig: { metric: 1, scaleMax: 0.02, trials: 8000 },
        question: 'What is the probability both cards are aces? (decimal)',
        answer: (4 / 52) * (3 / 51),
        tolerance: 0.004,
        unit: 'probability',
        feedback: {
          correct: 'Exactly — multiply the conditional steps: (4/52)(3/51) ≈ 0.0045.',
          incorrect: 'Chain the two draws: (4/52)(3/51) ≈ 0.0045. Conditional probabilities multiply.',
        },
      },
    ],
  },
  {
    id: 'l7-monty-hall',
    index: 7,
    title: 'The Monty Hall Problem',
    concept: 'Why switching wins',
    status: 'built',
    prerequisiteId: 'l6-conditional',
    steps: [
      {
        id: 'l7-s1',
        type: 'concept',
        title: 'Three doors, one car',
        body: 'You pick one of three doors. The host, who knows where the car is, opens a different door revealing a goat, then offers you the chance to switch. Does switching help? Toggle the strategy and play many rounds — the win rates tell a clear story.',
        simulation: 'montyHall',
        simConfig: { doors: 3 },
      },
      {
        id: 'l7-s2',
        type: 'problem',
        title: 'Sticking with your door',
        body: 'You always keep your original door, no matter which goat the host reveals.',
        simulation: 'montyHall',
        simConfig: { doors: 3, strategy: 0, trials: 1500 },
        question: 'What fraction of games do you win by staying? (decimal)',
        answer: 1 / 3,
        tolerance: 0.05,
        unit: 'fraction',
        feedback: {
          correct: 'Right — staying wins only when your first guess was correct, which is 1/3.',
          incorrect: 'Staying only wins if your initial pick was right: that is 1/3 ≈ 0.33.',
        },
      },
      {
        id: 'l7-s3',
        type: 'problem',
        title: 'Always switching',
        body: 'Now you always switch to the other unopened door after the host reveals a goat.',
        simulation: 'montyHall',
        simConfig: { doors: 3, strategy: 1, trials: 1500 },
        question: 'What fraction of games do you win by switching? (decimal)',
        answer: montyHallSwitchWin(3),
        tolerance: 0.05,
        unit: 'fraction',
        feedback: {
          correct: 'Yes — switching wins whenever your first pick was wrong, which is 2/3. It doubles your odds.',
          incorrect: 'Switching wins exactly when your first guess was wrong — that happens 2/3 of the time.',
        },
      },
      {
        id: 'l7-s4',
        type: 'problem',
        title: 'A hundred doors',
        body: 'Imagine 100 doors. You pick one, and the host opens 98 other doors, all goats, leaving just yours and one other. You switch.',
        simulation: 'montyHall',
        simConfig: { doors: 100, strategy: 1, trials: 1500 },
        question: 'What fraction of games do you win by switching now? (decimal)',
        answer: montyHallSwitchWin(100),
        tolerance: 0.05,
        unit: 'fraction',
        feedback: {
          correct: 'Exactly — 99/100. With 100 doors the intuition finally clicks: your first pick is almost always wrong, so switching almost always wins.',
          incorrect: 'Your first pick is right only 1/100 of the time, so switching wins the other 99/100 ≈ 0.99.',
        },
      },
    ],
  },
];

export function getLesson(id: string): Lesson | undefined {
  return lessons.find((l) => l.id === id);
}

export function gradableSteps(lesson: Lesson) {
  return lesson.steps.filter((s) => s.type === 'problem');
}
