import type { Lesson } from '../types/lesson';
import {
  longRunFrequency,
  mostLikelyDiceSumProbability,
  diceSumDistribution,
  binomialPmf,
  galtonCenterFraction,
  montyHallSwitchWin,
  sumsByLikelihood,
  rankBy,
  randomWalkDrift,
  randomWalkRMS,
  randomWalkEndDistribution,
  dieMean,
  dieSD,
  standardError,
  diceSampleMeanDistribution,
  drawProbability,
  drawMatchesNoReplacement,
} from '../lib/probability';
import { wheelConfig, wheelEV } from './simData';

const dice = diceSumDistribution();
const cltMean10 = diceSampleMeanDistribution(10);
const walkEndBias = randomWalkEndDistribution(100, 0.6);

const dieWheel = [1, 2, 3, 4, 5, 6].map((v) => ({ value: v, p: 1 / 6 }));
const lotteryWheel = [
  { value: 0, p: 0.9 },
  { value: 100, p: 0.1 },
];
const prizeWheel = [
  { value: 1, p: 0.5 },
  { value: 5, p: 0.3 },
  { value: 10, p: 0.2 },
];
const coinGame = [
  { value: 2, p: 0.5 },
  { value: 0, p: 0.5 },
];
const mixWheel = [
  { value: 0, p: 0.7 },
  { value: 5, p: 0.2 },
  { value: 20, p: 0.1 },
];

/**
 * The course. Lessons 1-3 are fully built and playable. Lessons 4-7 ship as
 * `coming-soon` so the full intended depth is visible without claiming it works.
 * Every numeric `answer` is computed by the owned probability functions above.
 */
export const lessons: Lesson[] = [
  {
    id: 'l1-coin-flip',
    index: 1,
    title: 'What is Probability?',
    concept: 'Long-run frequency',
    status: 'built',
    prerequisiteId: null,
    steps: [
      {
        id: 'l1-s1',
        type: 'concept',
        title: 'Flip until it clicks',
        body: 'Probability is what happens in the long run. Drag the slider to flip a coin many times and watch the fraction of heads settle toward one half. A few flips are wild and lopsided; thousands of flips are remarkably steady.',
        simulation: 'coinFlip',
        simConfig: { flips: 100, p: 0.5 },
        lecture: [
          {
            heading: 'The frequentist definition',
            text: 'The probability of an event is the value its relative frequency approaches as the number of independent trials grows without bound. If an event $A$ occurs $N_A$ times in $N$ trials, we define $P(A)$ as the limit of $N_A / N$ as $N \\to \\infty$. For a fair coin, that limit is exactly $1/2$.',
            formula: 'P(A) = \\lim_{N \\to \\infty} \\frac{N_A}{N}',
          },
          {
            heading: 'The Law of Large Numbers',
            text: 'Model each flip as an indicator $X_i$ that equals $1$ for heads and $0$ for tails, with mean $E[X_i] = p$. The running fraction of heads is the sample mean of these variables. The Law of Large Numbers guarantees this average converges to $p$: for any tolerance $\\varepsilon > 0$, the probability that the average sits more than $\\varepsilon$ from $p$ tends to zero.',
            formula: '\\bar{X}_N = \\frac{1}{N}\\sum_{i=1}^{N} X_i \\;\\longrightarrow\\; p',
          },
          {
            heading: 'How fast does it settle?',
            text: 'Convergence is gradual, not instant. The standard deviation of the running average is $\\sqrt{p(1-p)/N}$, which shrinks like $1/\\sqrt{N}$. That is why a handful of flips look wildly lopsided while thousands look smooth — and why halving the typical error requires four times as many trials.',
            formula: '\\operatorname{SD}(\\bar{X}_N) = \\sqrt{\\dfrac{p(1-p)}{N}}',
          },
          {
            heading: 'No memory: the gambler’s fallacy',
            text: 'Each flip is independent, so conditioning on the past changes nothing: $P(\\text{heads} \\mid \\text{history}) = p$. A streak of heads does not make tails “due.” The long-run average is restored by dilution across many future trials, never by a corrective force acting on the next flip.',
          },
        ],
      },
      {
        id: 'l1-s2',
        type: 'problem',
        title: 'Predict the long run',
        body: 'You are about to flip a fair coin 1000 times.',
        simulation: 'coinFlip',
        simConfig: { flips: 1000, p: 0.5 },
        question: 'What fraction of the 1000 flips will come up heads? (enter a decimal, e.g. 0.5)',
        answer: longRunFrequency(0.5),
        tolerance: 0.05,
        unit: 'fraction',
        feedback: {
          correct: 'Exactly. A fair coin has no memory and no preference — over many flips the fraction of heads converges to one half.',
          incorrect: 'Close, but a fair coin converges to 0.5. Each flip is 50/50, so over 1000 flips roughly half land heads.',
        },
      },
      {
        id: 'l1-s3',
        type: 'problem',
        title: 'When the coin is bent',
        body: 'Now the coin is biased: it lands heads 75% of the time on each flip.',
        simulation: 'coinFlip',
        simConfig: { flips: 1000, p: 0.75 },
        question: 'Over 1000 flips of this biased coin, what fraction will be heads?',
        answer: longRunFrequency(0.75),
        tolerance: 0.05,
        unit: 'fraction',
        feedback: {
          correct: 'Right. Long-run frequency converges to the true probability of the process — here that is 0.75.',
          incorrect: 'The frequency converges to the coin’s actual bias. If every flip is 75% heads, about 0.75 of all flips are heads.',
        },
      },
      {
        id: 'l1-s4',
        type: 'problem',
        title: 'The gambler’s trap',
        body: 'You flip a fair coin 10 times and happen to get 7 heads.',
        simulation: 'coinFlip',
        simConfig: { flips: 1000, p: 0.5 },
        question: 'Continuing with the same fair coin, what fraction of the next 1000 flips do you predict are heads?',
        answer: longRunFrequency(0.5),
        tolerance: 0.05,
        unit: 'fraction',
        feedback: {
          correct: 'Yes — the coin has no memory. A streak of heads does not make tails “due.” The long run is still 0.5.',
          incorrect: 'A fair coin does not correct for past streaks. The next 1000 flips still converge to 0.5, regardless of what just happened.',
        },
      },
      {
        id: 'l1-s5',
        type: 'problem',
        title: 'A coin that mostly tails',
        body: 'This coin is biased the other way: it lands heads only 30% of the time on each flip.',
        simulation: 'coinFlip',
        simConfig: { flips: 1000, p: 0.3 },
        question: 'Over 1000 flips, what fraction will be heads? (decimal)',
        answer: longRunFrequency(0.3),
        tolerance: 0.05,
        unit: 'fraction',
        feedback: {
          correct: 'Right — the frequency homes in on the coin’s true bias, 0.30.',
          incorrect: 'Each flip is 30% heads, so over many flips about 0.30 of them land heads.',
        },
      },
      {
        id: 'l1-s6',
        type: 'problem',
        title: 'Almost always heads',
        body: 'A nearly two-headed coin lands heads 90% of the time on each flip.',
        simulation: 'coinFlip',
        simConfig: { flips: 1000, p: 0.9 },
        question: 'What fraction of 1000 flips will be heads? (decimal)',
        answer: longRunFrequency(0.9),
        tolerance: 0.05,
        unit: 'fraction',
        feedback: {
          correct: 'Exactly — the long-run fraction equals the bias, 0.90.',
          incorrect: 'The fraction converges to the true probability of heads, which is 0.90.',
        },
      },
    ],
  },
  {
    id: 'l2-dice-roll',
    index: 2,
    title: 'Independent Events',
    concept: 'Combining independent outcomes',
    status: 'built',
    prerequisiteId: 'l1-coin-flip',
    steps: [
      {
        id: 'l2-s1',
        type: 'concept',
        title: 'Two dice, many sums',
        body: 'Each die is independent — one roll never affects the other. But when you add two dice, the sums are not equally likely. Roll many times and watch the histogram of sums build into a triangle.',
        simulation: 'diceRoll',
        simConfig: { rolls: 100 },
        lecture: [
          {
            heading: 'Independent events multiply',
            text: 'Two events are independent when the occurrence of one tells you nothing about the other. For independent events, the probability that both occur is the product of their probabilities. Each die is a uniform draw from $\\{1,\\dots,6\\}$, and one die never influences the other.',
            formula: 'P(A \\cap B) = P(A)\\,P(B)',
          },
          {
            heading: 'The sample space of two dice',
            text: 'Rolling two dice yields $36$ equally likely ordered outcomes $(a, b)$. When outcomes are equally likely, the probability of an event is just the count of favorable outcomes over the total — the classical (Laplace) definition of probability.',
            formula: 'P(E) = \\frac{|E|}{|\\Omega|} = \\frac{\\#\\,\\text{favorable}}{36}',
          },
          {
            heading: 'Why the sums are not uniform',
            text: 'Although every ordered pair is equally likely, their sums are not. The number of ways to make each sum forms a triangle: just one way to make $2$ or $12$, but six ways to make $7$. The distribution of the sum is the convolution of two uniform distributions.',
            formula: 'P(S = s) = \\frac{\\#\\,\\{(a,b) : a+b = s\\}}{36}',
          },
          {
            heading: 'The peak at seven',
            text: 'Seven is reachable from every face of the first die paired with a complementary face of the second (1+6, 2+5, 3+4, and their reverses). More decompositions mean higher probability, so 7 sits at the peak with probability 6/36 = 1/6.',
          },
        ],
      },
      {
        id: 'l2-s5',
        type: 'problem',
        title: 'Sketch the sum distribution',
        body: 'Across the 36 equally likely outcomes, some sums have far more combinations than others.',
        simulation: 'diceRoll',
        simConfig: { rolls: 2000 },
        question: 'Sketch how often each sum from 2 to 12 should appear, then roll to compare.',
        interaction: 'draw',
        drawCategories: Array.from({ length: 11 }, (_, i) => i + 2),
        answerShape: Array.from({ length: 11 }, (_, i) => dice[i + 2]),
        tolerance: 0.18,
        unit: 'shape',
        feedback: {
          correct: 'Exactly — a symmetric triangle peaking at 7, tapering to the rare 2 and 12 at the edges.',
          incorrect: 'The shape is a triangle: 7 is most likely (6 ways), falling to 2 and 12 (one way each).',
        },
      },
      {
        id: 'l2-s6',
        type: 'problem',
        title: 'Rank the sums',
        body: 'Not every sum is equally likely — what matters is how many of the 36 outcomes produce each one.',
        simulation: 'diceRoll',
        simConfig: { rolls: 2000 },
        question: 'Rank these four sums from most to least likely, then roll to check.',
        interaction: 'order',
        orderItems: [2, 5, 7, 10],
        answerOrder: sumsByLikelihood([2, 5, 7, 10]),
        unit: 'order',
        feedback: {
          correct:
            'Exactly — 7 (six ways) beats 5 (four) beats 10 (three) beats 2 (one). More combinations means higher probability.',
          incorrect:
            'Count the ways to make each sum: 7→6, 5→4, 10→3, 2→1. That count is the ranking, most to least likely.',
        },
      },
      {
        id: 'l2-s2',
        type: 'problem',
        title: 'The peak of the triangle',
        body: 'There are 36 equally likely ways two dice can land.',
        simulation: 'diceRoll',
        simConfig: { rolls: 2000 },
        question: 'Which sum is the single most likely? (enter the number)',
        answer: 7,
        tolerance: 0.5,
        unit: 'sum',
        feedback: {
          correct: 'Right — 7 has the most combinations (1+6, 2+5, 3+4, and their reverses): six ways out of 36.',
          incorrect: 'The most likely sum is 7. It can be made six different ways, more than any other sum.',
        },
      },
      {
        id: 'l2-s3',
        type: 'problem',
        title: 'How likely is seven?',
        body: 'Seven can be rolled six ways out of 36 total outcomes.',
        simulation: 'diceRoll',
        simConfig: { rolls: 2000 },
        question: 'What is the probability of rolling a sum of 7? (decimal)',
        answer: mostLikelyDiceSumProbability(),
        tolerance: 0.02,
        unit: 'probability',
        feedback: {
          correct: 'Exactly — 6 favorable outcomes out of 36 is 1/6 ≈ 0.167.',
          incorrect: 'There are 6 ways to make 7 out of 36 outcomes: 6/36 = 1/6 ≈ 0.167.',
        },
      },
      {
        id: 'l2-s4',
        type: 'problem',
        title: 'Snake eyes',
        body: 'A sum of 2 requires both dice to show 1.',
        simulation: 'diceRoll',
        simConfig: { rolls: 2000 },
        question: 'What is the probability of rolling a sum of 2? (decimal)',
        answer: dice[2],
        tolerance: 0.02,
        unit: 'probability',
        feedback: {
          correct: 'Right — only one outcome (1,1) out of 36, so 1/36 ≈ 0.028. Extremes are rare.',
          incorrect: 'Only (1,1) makes a 2 — one way out of 36, so 1/36 ≈ 0.028.',
        },
      },
    ],
  },
  {
    id: 'l3-galton-board',
    index: 3,
    title: 'The Galton Board',
    concept: 'How the bell curve emerges',
    status: 'built',
    prerequisiteId: 'l2-dice-roll',
    steps: [
      {
        id: 'l3-s1',
        type: 'concept',
        title: 'Build a bell curve from chance',
        body: 'Each ball bounces left or right at every peg — a coin flip at each row. Independent random choices, stacked together, pile up into a bell-shaped curve. Drop some balls and watch the bins fill.',
        simulation: 'galtonBoard',
        simConfig: { rows: 12, balls: 200 },
        lecture: [
          {
            heading: 'A machine that builds a binomial',
            text: 'At each of the $n$ rows, a ball bounces left or right with probability $1/2$ — an independent Bernoulli trial. The bin it ends in equals its number of right-bounces, so the bin index $K$ follows a $\\text{Binomial}(n, 1/2)$ distribution.',
            formula: 'P(K = k) = \\binom{n}{k}\\left(\\tfrac{1}{2}\\right)^{n}',
          },
          {
            heading: 'Counting paths',
            text: 'The binomial coefficient $\\binom{n}{k}$ counts how many distinct left/right paths arrive at bin $k$. The central bins are reachable by exponentially many paths, while each extreme bin has exactly one path — all-left or all-right — which is why the edges stay nearly empty.',
            formula: '\\binom{n}{k} = \\frac{n!}{k!\\,(n-k)!}',
          },
          {
            heading: 'The Central Limit Theorem',
            text: 'A bin count is a sum of many independent shocks. The Central Limit Theorem says that, once standardized, such sums converge to the standard normal distribution as $n$ grows. This is why independent randomness, stacked up, reliably yields the bell curve — it is a universal limit, not a coincidence of this device.',
            formula: '\\frac{K - np}{\\sqrt{np(1-p)}} \\;\\longrightarrow\\; \\mathcal{N}(0, 1)',
          },
          {
            heading: 'Center and spread',
            text: 'For $n$ rows with $p = 1/2$, the mean bin is $np = n/2$ and the variance is $np(1-p) = n/4$, so the spread grows only like $\\sqrt{n}/2$. The bulk of outcomes lies within a few standard deviations of center, and the two outermost bins together hold only $2\\cdot(1/2)^n$ of the probability.',
          },
        ],
      },
      {
        id: 'l3-s6',
        type: 'problem',
        title: 'Sketch the bell curve',
        body: 'Before dropping the balls, predict the whole shape — how full each of the 13 bins will be.',
        simulation: 'galtonBoard',
        simConfig: { rows: 12, balls: 1000 },
        question: 'Drag to sketch the distribution across the 13 bins, then drop the balls to compare.',
        interaction: 'draw',
        drawCategories: Array.from({ length: 13 }, (_, k) => k),
        answerShape: Array.from({ length: 13 }, (_, k) => binomialPmf(12, k, 0.5)),
        tolerance: 0.18,
        unit: 'shape',
        feedback: {
          correct:
            'Beautiful — a tall, symmetric bell. The center bins tower over the edges, exactly as the binomial predicts.',
          incorrect:
            'The true shape is a symmetric bell: tallest in the middle, vanishing at the edges. Yours was too flat or too lopsided.',
        },
      },
      {
        id: 'l3-s2',
        type: 'problem',
        title: 'Where do the balls pile up?',
        body: 'This board has 12 rows, so balls collect in 13 bins. Most pile up in the middle.',
        simulation: 'galtonBoard',
        simConfig: { rows: 12, balls: 1000 },
        question: 'What fraction of balls land in the three central bins? (decimal)',
        answer: galtonCenterFraction(12, 3),
        tolerance: 0.06,
        unit: 'fraction',
        feedback: {
          correct: 'Yes — the center dominates. Around 61% of balls land in just the three middle bins.',
          incorrect: 'The three central bins hold the bulk of the balls — about 0.61 of them. The middle is by far the most likely place to land.',
        },
      },
      {
        id: 'l3-s3',
        type: 'problem',
        title: 'The single peak',
        body: 'The exact center bin corresponds to an equal number of left and right bounces.',
        simulation: 'galtonBoard',
        simConfig: { rows: 12, balls: 1000 },
        question: 'What fraction of balls land in the one exact-center bin? (decimal)',
        answer: binomialPmf(12, 6, 0.5),
        tolerance: 0.03,
        unit: 'fraction',
        feedback: {
          correct: 'Right — about 0.23. Even the single most likely bin only gets roughly a quarter of the balls.',
          incorrect: 'The center bin gets about 0.23 of the balls — the most of any single bin, but still under a quarter.',
        },
      },
      {
        id: 'l3-s4',
        type: 'problem',
        title: 'The lonely edges',
        body: 'The two outermost bins require a ball to bounce the same direction at every single peg.',
        simulation: 'galtonBoard',
        simConfig: { rows: 12, balls: 1000 },
        question: 'What fraction of balls land in the two outermost bins combined? (decimal)',
        answer: binomialPmf(12, 0, 0.5) + binomialPmf(12, 12, 0.5),
        tolerance: 0.02,
        unit: 'fraction',
        feedback: {
          correct: 'Exactly — almost none. Bouncing the same way 12 times in a row is vanishingly rare (about 0.0005).',
          incorrect: 'The edges are nearly empty — about 0.0005. Hitting all-left or all-right twelve times running almost never happens.',
        },
      },
      {
        id: 'l3-s5',
        type: 'problem',
        title: 'The wider middle',
        body: 'Widen the window to the five central bins of the 13.',
        simulation: 'galtonBoard',
        simConfig: { rows: 12, balls: 1000 },
        question: 'What fraction of balls land in the five central bins? (decimal)',
        answer: galtonCenterFraction(12, 5),
        tolerance: 0.05,
        unit: 'fraction',
        feedback: {
          correct: 'Right — about 0.85. Widen the window a little and you capture the vast majority.',
          incorrect: 'The five central bins hold roughly 0.85 of the balls — almost everything.',
        },
      },
    ],
  },
  {
    id: 'l5-expected-value',
    index: 4,
    title: 'Expected Value',
    concept: 'Weighted average of outcomes',
    status: 'built',
    prerequisiteId: 'l3-galton-board',
    steps: [
      {
        id: 'l5-s1',
        type: 'concept',
        title: 'The long-run average',
        body: 'Expected value is the average payout you would get per try if you repeated a game forever. It is each outcome weighted by its probability. Spin the prize wheel many times and watch the running average settle on a single number — that number is the expected value.',
        simulation: 'expectedValue',
        simConfig: wheelConfig(prizeWheel),
        lecture: [
          {
            heading: 'Definition of expected value',
            text: 'The expected value of a discrete random variable is the sum of its outcomes, each weighted by its probability. It is the probability-weighted average — equivalently, the center of mass of the distribution.',
            formula: 'E[X] = \\sum_i x_i \\, P(X = x_i)',
          },
          {
            heading: 'It is the long-run average',
            text: 'By the Law of Large Numbers, the average payout over many independent plays converges to E[X]. The running average you watch on the wheel is settling onto exactly this number, which is why expected value predicts long-term performance.',
          },
          {
            heading: 'Not necessarily attainable',
            text: 'Expected value is a balance point, not a typical outcome. A fair six-sided die has $E[X] = 3.5$ even though you can never roll a $3.5$. Read it as where the distribution balances, not as a value you expect to see on any single try.',
            formula: 'E[\\text{die}] = \\frac{1+2+3+4+5+6}{6} = 3.5',
          },
          {
            heading: 'Linearity of expectation',
            text: 'Expectation is linear: the expected value of a sum is the sum of the expected values, scaling included — and remarkably, this holds even when the variables are dependent. Linearity is the workhorse that lets you split a complicated payoff into simple pieces.',
            formula: 'E[aX + bY] = a\\,E[X] + b\\,E[Y]',
          },
          {
            heading: 'Fair games and the house edge',
            text: 'A wager is fair when its expected payout equals its cost. Lotteries and casinos deliberately price bets so that expected value falls short of the cost — that gap is the house edge, and it is why the house wins over the long run.',
          },
        ],
      },
      {
        id: 'l5-s6',
        type: 'problem',
        title: 'Rank the games by value',
        body: 'Four games, four payout structures. Expected value — each payout times its chance, summed — says which is worth the most per play.',
        simulation: 'expectedValue',
        simConfig: wheelConfig(mixWheel),
        question: 'Rank these games from highest to lowest expected payout.',
        interaction: 'order',
        orderItems: [0, 1, 2, 3],
        orderLabels: {
          0: 'Coin game: $2 half the time, else $0',
          1: 'Mix wheel: $5 (20%), $20 (10%), else $0',
          2: 'Prize wheel: $1 (50%), $5 (30%), $10 (20%)',
          3: 'Lottery: $100 (10%), else $0',
        },
        answerOrder: rankBy([0, 1, 2, 3], (i) => wheelEV([coinGame, mixWheel, prizeWheel, lotteryWheel][i])),
        unit: 'order',
        feedback: {
          correct: 'Right — by expected value: lottery $10 > prize wheel $4 > mix wheel $3 > coin game $1.',
          incorrect: 'Weight each payout by its chance and add: lottery $10, prize $4, mix $3, coin $1.',
        },
      },
      {
        id: 'l5-s2',
        type: 'problem',
        title: 'The prize wheel',
        body: 'This wheel pays $1 half the time, $5 with probability 0.3, and $10 with probability 0.2.',
        simulation: 'expectedValue',
        simConfig: wheelConfig(prizeWheel),
        question: 'What is the expected payout of a single spin? (dollars)',
        answer: wheelEV(prizeWheel),
        tolerance: 0.4,
        unit: 'dollars',
        feedback: {
          correct: 'Right — 1(0.5) + 5(0.3) + 10(0.2) = $4.00. The average lands between the outcomes, weighted by their chances.',
          incorrect: 'Weight each prize by its probability: 1(0.5) + 5(0.3) + 10(0.2) = $4.00.',
        },
      },
      {
        id: 'l5-s3',
        type: 'problem',
        title: 'A roll of the die',
        body: 'A game pays you, in dollars, whatever a fair six-sided die shows.',
        simulation: 'expectedValue',
        simConfig: wheelConfig(dieWheel),
        question: 'What is the expected payout of one roll? (dollars)',
        answer: wheelEV(dieWheel),
        tolerance: 0.4,
        unit: 'dollars',
        feedback: {
          correct: 'Yes — (1+2+3+4+5+6)/6 = 3.5. Expected value need not be a value you can actually roll.',
          incorrect: 'Average the six equally likely faces: (1+2+3+4+5+6)/6 = $3.50.',
        },
      },
      {
        id: 'l5-s4',
        type: 'problem',
        title: 'The long-shot lottery',
        body: 'A ticket pays $100 with probability 0.1, and nothing otherwise.',
        simulation: 'expectedValue',
        simConfig: wheelConfig(lotteryWheel),
        question: 'What is the expected value of one ticket? (dollars)',
        answer: wheelEV(lotteryWheel),
        tolerance: 1,
        unit: 'dollars',
        feedback: {
          correct: 'Right — 100(0.1) + 0(0.9) = $10. A rare big prize still has a modest expected value.',
          incorrect: 'A 0.1 chance at $100 is worth 100 × 0.1 = $10 on average.',
        },
      },
      {
        id: 'l5-s5',
        type: 'problem',
        title: 'A simple coin game',
        body: 'A game pays $2 if a fair coin lands heads, and $0 if it lands tails.',
        simulation: 'expectedValue',
        simConfig: wheelConfig(coinGame),
        question: 'What is the expected payout per play? (dollars)',
        answer: wheelEV(coinGame),
        tolerance: 0.3,
        unit: 'dollars',
        feedback: {
          correct: 'Right — 2(0.5) + 0(0.5) = $1.00.',
          incorrect: 'Weight each payout by its chance: 2(0.5) + 0(0.5) = $1.00.',
        },
      },
    ],
  },
  {
    id: 'l6-conditional',
    index: 5,
    title: 'Conditional Probability',
    concept: 'Updating on new information',
    status: 'built',
    prerequisiteId: 'l5-expected-value',
    steps: [
      {
        id: 'l6-s1',
        type: 'concept',
        title: 'Information changes the odds',
        body: 'A conditional probability is the chance of an event given that something else has already happened. Drawing cards without replacement is the cleanest example: once a card is gone, the deck — and every probability — changes. Deal many times and watch the fractions settle.',
        simulation: 'conditional',
        simConfig: { metric: 0, scaleMax: 0.15 },
        lecture: [
          {
            heading: 'Definition of conditional probability',
            text: 'The conditional probability of $A$ given $B$ restricts the sample space to outcomes where $B$ occurs, then asks how often $A$ also holds. It is defined as the joint probability divided by the probability of the condition (requiring $P(B) > 0$).',
            formula: 'P(A \\mid B) = \\frac{P(A \\cap B)}{P(B)}',
          },
          {
            heading: 'The multiplication (chain) rule',
            text: 'Rearranging the definition gives the chain rule: the probability that both $A$ and $B$ happen is the probability of $A$ times the probability of $B$ given $A$. For draws without replacement the deck shrinks after each draw, so these conditional probabilities change as you go.',
            formula: 'P(A \\cap B) = P(A)\\,P(B \\mid A)',
          },
          {
            heading: 'Drawing without replacement',
            text: 'Two aces in a row show the chain rule directly. The first ace has probability $4/52$; given it is set aside, the second has probability $3/51$. Both the numerator and the denominator update because a card was removed from the deck.',
            formula: 'P(\\text{ace, then ace}) = \\frac{4}{52}\\cdot\\frac{3}{51}',
          },
          {
            heading: 'Independence as a special case',
            text: 'Events $A$ and $B$ are independent exactly when conditioning on $B$ does not change $A$ — equivalently, when the joint probability factors into the product of the two. Drawing with replacement restores independence, since the deck returns to its original state each time.',
            formula: 'A \\perp B \\iff P(A \\mid B) = P(A) \\iff P(A \\cap B) = P(A)P(B)',
          },
          {
            heading: 'Toward Bayes’ theorem',
            text: 'Conditioning can be reversed. Writing the joint probability two ways and equating them yields Bayes’ theorem — the rule for updating a belief about $A$ after observing $B$. It is the formal engine behind learning from evidence.',
            formula: 'P(A \\mid B) = \\frac{P(B \\mid A)\\,P(A)}{P(B)}',
          },
        ],
      },
      {
        id: 'l6-s2',
        type: 'problem',
        title: 'The first card',
        body: 'You draw one card from a freshly shuffled 52-card deck.',
        simulation: 'conditional',
        simConfig: { metric: 0, scaleMax: 0.15, trials: 6000 },
        question: 'What is the probability it is an ace? (decimal)',
        answer: drawProbability(4, 52),
        tolerance: 0.02,
        unit: 'probability',
        feedback: {
          correct: 'Right — 4 aces out of 52 cards is 1/13 ≈ 0.077.',
          incorrect: 'There are 4 aces in 52 cards: 4/52 = 1/13 ≈ 0.077.',
        },
      },
      {
        id: 'l6-s3',
        type: 'problem',
        title: 'Given the first was an ace',
        body: 'Your first card was an ace and you set it aside. Now 51 cards remain, 3 of them aces.',
        simulation: 'conditional',
        simConfig: { metric: 2, scaleMax: 0.15, trials: 8000 },
        question: 'What is the probability the next card is also an ace? (decimal)',
        answer: drawProbability(3, 51),
        tolerance: 0.02,
        unit: 'probability',
        feedback: {
          correct: 'Yes — conditioning on the first ace leaves 3 aces in 51 cards: 3/51 ≈ 0.059.',
          incorrect: 'After removing one ace, 3 aces remain among 51 cards: 3/51 ≈ 0.059.',
        },
      },
      {
        id: 'l6-s4',
        type: 'problem',
        title: 'Both at once',
        body: 'You draw two cards from a full deck. The two events combine: ace first, then ace again.',
        simulation: 'conditional',
        simConfig: { metric: 1, scaleMax: 0.02, trials: 8000 },
        question: 'What is the probability both cards are aces? (decimal)',
        answer: drawMatchesNoReplacement(4, 52, 2),
        tolerance: 0.004,
        unit: 'probability',
        feedback: {
          correct: 'Exactly — multiply the conditional steps: (4/52)(3/51) ≈ 0.0045.',
          incorrect: 'Chain the two draws: (4/52)(3/51) ≈ 0.0045. Conditional probabilities multiply.',
        },
      },
      {
        id: 'l6-s5',
        type: 'problem',
        title: 'Drawing a face card',
        body: 'A face card is a Jack, Queen, or King — 12 of the 52 cards.',
        simulation: 'conditional',
        simConfig: { metric: 3, scaleMax: 0.4, trials: 6000 },
        question: 'What is the probability the first card drawn is a face card? (decimal)',
        answer: drawProbability(12, 52),
        tolerance: 0.03,
        unit: 'probability',
        feedback: {
          correct: 'Right — 12 face cards in 52 is 3/13 ≈ 0.231.',
          incorrect: 'There are 12 face cards in 52: 12/52 = 3/13 ≈ 0.231.',
        },
      },
      {
        id: 'l6-s6',
        type: 'problem',
        title: 'Rank the events',
        body: 'Conditioning reshapes the odds: removing a card changes what is left. Four events, four different probabilities.',
        simulation: 'conditional',
        simConfig: { metric: 3, scaleMax: 0.4, trials: 6000 },
        question: 'Rank these four events from most to least likely.',
        interaction: 'order',
        orderItems: [0, 1, 2, 3],
        orderLabels: {
          0: 'An ace on the first draw',
          1: 'An ace next, given the first card was an ace',
          2: 'An ace next, given the first card was not an ace',
          3: 'A face card on the first draw',
        },
        answerOrder: rankBy(
          [0, 1, 2, 3],
          (i) => [drawProbability(4, 52), drawProbability(3, 51), drawProbability(4, 51), drawProbability(12, 52)][i],
        ),
        unit: 'order',
        feedback: {
          correct: 'Right — face card .231 > ace-given-non-ace .078 > ace .077 > ace-given-ace .059. Removing a non-ace lifts the ace odds; removing an ace lowers them.',
          incorrect: 'Compare the fractions: 12/52, then 4/51, then 4/52, then 3/51 — removing a non-ace nudges the ace odds up, an ace down.',
        },
      },
    ],
  },
  {
    id: 'l7-monty-hall',
    index: 6,
    title: 'The Monty Hall Problem',
    concept: 'Why switching wins',
    status: 'built',
    prerequisiteId: 'l6-conditional',
    steps: [
      {
        id: 'l7-s1',
        type: 'concept',
        title: 'Three doors, one car',
        body: 'You pick one of three doors. The host, who knows where the car is, opens a different door revealing a goat, then offers you the chance to switch. Does switching help? Toggle the strategy and play many rounds — the win rates tell a clear story.',
        simulation: 'montyHall',
        simConfig: { doors: 3 },
        lecture: [
          {
            heading: 'The host changes everything',
            text: 'The crucial feature of Monty Hall is that the host knows where the car is and always opens a door revealing a goat. That reveal is not random — it is a deliberate, filtered action that injects information into the game.',
          },
          {
            heading: 'Your door is frozen at 1/3',
            text: 'When you first choose, the probability the car is behind your door is $1/3$, and the probability it is behind one of the other two is $2/3$. The host opening a goat does not raise your door’s $1/3$ — instead it collapses that entire $2/3$ onto the single remaining unopened door.',
            formula: 'P(\\text{your door}) = \\tfrac{1}{3}, \\quad P(\\text{the other}) = \\tfrac{2}{3}',
          },
          {
            heading: 'Generalizing to n doors',
            text: 'With $n$ doors you pick one (probability $1/n$ of being right) and the host opens $n - 2$ goats. Staying wins only when your first pick was correct, while switching wins whenever it was wrong. The advantage of switching grows as the number of doors increases.',
            formula: 'P(\\text{win} \\mid \\text{stay}) = \\tfrac{1}{n}, \\quad P(\\text{win} \\mid \\text{switch}) = \\tfrac{n-1}{n}',
          },
          {
            heading: 'Why intuition rebels',
            text: 'Seeing two closed doors at the end, people assume 50/50 and treat them as symmetric. They are not: the host’s knowledgeable reveal concentrates the leftover probability onto the switch door. With 100 doors the asymmetry becomes obvious — switching wins 99 times out of 100.',
          },
        ],
      },
      {
        id: 'l7-s6',
        type: 'problem',
        title: 'Rank the switch advantage',
        body: 'Switching wins whenever your first pick was wrong — and a wrong first pick gets more likely as doors are added.',
        simulation: 'montyHall',
        simConfig: { doors: 10, strategy: 1, trials: 1500 },
        question: 'Rank these games by your win chance if you always switch, highest first.',
        interaction: 'order',
        orderItems: [3, 10, 100],
        orderLabels: { 3: '3 doors', 10: '10 doors', 100: '100 doors' },
        answerOrder: rankBy([3, 10, 100], (d) => montyHallSwitchWin(d)),
        unit: 'order',
        feedback: {
          correct: 'Right — switching wins (n−1)/n: 100 doors → 0.99, 10 → 0.90, 3 → 0.67. More doors, bigger edge.',
          incorrect: 'Switching wins (n−1)/n, which grows with n — so 100 doors beats 10 doors beats 3 doors.',
        },
      },
      {
        id: 'l7-s2',
        type: 'problem',
        title: 'Sticking with your door',
        body: 'You always keep your original door, no matter which goat the host reveals.',
        simulation: 'montyHall',
        simConfig: { doors: 3, strategy: 0, trials: 1500 },
        question: 'What fraction of games do you win by staying? (decimal)',
        answer: 1 / 3,
        tolerance: 0.05,
        unit: 'fraction',
        feedback: {
          correct: 'Right — staying wins only when your first guess was correct, which is 1/3.',
          incorrect: 'Staying only wins if your initial pick was right: that is 1/3 ≈ 0.33.',
        },
      },
      {
        id: 'l7-s3',
        type: 'problem',
        title: 'Always switching',
        body: 'Now you always switch to the other unopened door after the host reveals a goat.',
        simulation: 'montyHall',
        simConfig: { doors: 3, strategy: 1, trials: 1500 },
        question: 'What fraction of games do you win by switching? (decimal)',
        answer: montyHallSwitchWin(3),
        tolerance: 0.05,
        unit: 'fraction',
        feedback: {
          correct: 'Yes — switching wins whenever your first pick was wrong, which is 2/3. It doubles your odds.',
          incorrect: 'Switching wins exactly when your first guess was wrong — that happens 2/3 of the time.',
        },
      },
      {
        id: 'l7-s4',
        type: 'problem',
        title: 'A hundred doors',
        body: 'Imagine 100 doors. You pick one, and the host opens 98 other doors, all goats, leaving just yours and one other. You switch.',
        simulation: 'montyHall',
        simConfig: { doors: 100, strategy: 1, trials: 1500 },
        question: 'What fraction of games do you win by switching now? (decimal)',
        answer: montyHallSwitchWin(100),
        tolerance: 0.05,
        unit: 'fraction',
        feedback: {
          correct: 'Exactly — 99/100. With 100 doors the intuition finally clicks: your first pick is almost always wrong, so switching almost always wins.',
          incorrect: 'Your first pick is right only 1/100 of the time, so switching wins the other 99/100 ≈ 0.99.',
        },
      },
      {
        id: 'l7-s5',
        type: 'problem',
        title: 'Staying with a hundred doors',
        body: 'Back to 100 doors. You pick one and refuse to switch, even after the host opens 98 goats.',
        simulation: 'montyHall',
        simConfig: { doors: 100, strategy: 0, trials: 1500 },
        question: 'What fraction of games do you win by staying? (decimal)',
        answer: 1 / 100,
        tolerance: 0.03,
        unit: 'fraction',
        feedback: {
          correct: 'Right — staying wins only if your 1-in-100 first pick was the car: 0.01.',
          incorrect: 'Staying wins only when your first pick was right — that is 1/100 = 0.01.',
        },
      },
    ],
  },
  {
    id: 'l9-clt',
    index: 7,
    title: 'The Central Limit Theorem',
    concept: 'Why averages go normal',
    status: 'built',
    prerequisiteId: 'l7-monty-hall',
    steps: [
      {
        id: 'l9-s1',
        type: 'concept',
        title: 'Averages find the bell',
        body: 'A single die roll is flat — 1 through 6 equally likely, nothing bell-shaped about it. But average several rolls together and repeat: those averages pile into a bell. Switch the parent to the lopsided distribution and it still happens. Raise the sample size and the bell tightens.',
        simulation: 'clt',
        simConfig: { parent: 0, m: 10, samples: 600 },
        lecture: [
          {
            heading: 'The sample mean',
            text: 'Draw $m$ independent values from any population and average them. This sample mean $\\bar{X}$ is itself random — run the experiment again and you get a different average. The CLT describes the distribution of those averages.',
            formula: '\\bar{X} = \\frac{1}{m}\\sum_{i=1}^{m} X_i',
          },
          {
            heading: 'The center never moves',
            text: 'Averaging introduces no bias: the expected value of the sample mean equals the population mean $\\mu$, whatever the sample size. The bell of averages is always centered on $\\mu$.',
            formula: 'E[\\bar{X}] = \\mu',
          },
          {
            heading: 'The spread shrinks like √m',
            text: 'Averages cluster more tightly than individual values. The standard deviation of the sample mean — the standard error — is the population SD divided by $\\sqrt{m}$. Quadruple the sample size and the spread halves.',
            formula: '\\operatorname{SE} = \\frac{\\sigma}{\\sqrt{m}}',
          },
          {
            heading: 'The shape becomes normal',
            text: 'The remarkable part: whatever the parent\u2019s shape — uniform, skewed, bumpy — the distribution of the sample mean approaches a normal curve as $m$ grows. This universality is why the bell appears wherever measurements are averaged.',
            formula: '\\bar{X} \\;\\approx\\; \\mathcal{N}\\!\\left(\\mu,\\; \\frac{\\sigma^2}{m}\\right)',
          },
          {
            heading: 'Reading the die',
            text: 'A fair die has mean $\\mu = 3.5$ and standard deviation $\\sigma = \\sqrt{35/12} \\approx 1.71$. These two numbers, plus the sample size, are all you need to predict where the bell of averages sits and how wide it is.',
          },
        ],
      },
      {
        id: 'l9-s6',
        type: 'problem',
        title: 'Sketch the bell of averages',
        body: 'Average 10 die rolls and repeat thousands of times. A flat die turns into a bell.',
        simulation: 'clt',
        simConfig: { parent: 0, m: 10, samples: 600 },
        question: 'Sketch the distribution of the sample mean (averages of 10 rolls), then run it to compare.',
        interaction: 'draw',
        drawCategories: cltMean10.categories,
        answerShape: cltMean10.shape,
        tolerance: 0.18,
        unit: 'shape',
        feedback: {
          correct: 'Beautiful — a bell centered on 3.5 (SE ≈ 0.54). Averaging a flat die produces the normal curve the CLT promises.',
          incorrect: 'The averages pile into a bell centered on 3.5 and fairly narrow (SE ≈ 0.54), not flat like a single die.',
        },
      },
      {
        id: 'l9-s2',
        type: 'problem',
        title: 'Center of the bell',
        body: 'You average 10 die rolls, then repeat thousands of times to build the distribution of sample means.',
        simulation: 'clt',
        simConfig: { parent: 0, m: 10, samples: 600 },
        question: 'Where is this distribution of sample means centered? (a value from 1 to 6)',
        answer: dieMean(),
        tolerance: 0.2,
        unit: 'value',
        feedback: {
          correct: 'Right — averaging is unbiased, so the bell centers on the die’s mean, 3.5, for any sample size.',
          incorrect: 'The sample mean shares the die’s mean: (1+2+3+4+5+6)/6 = 3.5.',
        },
      },
      {
        id: 'l9-s3',
        type: 'problem',
        title: 'How wide is it?',
        body: 'The die’s standard deviation is about 1.71. The averages spread far less than single rolls.',
        simulation: 'clt',
        simConfig: { parent: 0, m: 10, samples: 600 },
        question: 'What is the standard error (the SD of the sample mean) for samples of 10? (decimal)',
        answer: standardError(dieSD(), 10),
        tolerance: 0.06,
        unit: 'standard error',
        feedback: {
          correct: 'Exactly — 1.71 / √10 ≈ 0.54. The bell of averages is far narrower than the die itself.',
          incorrect: 'Standard error = σ/√m = 1.71/√10 ≈ 0.54.',
        },
      },
      {
        id: 'l9-s4',
        type: 'problem',
        title: 'Four times the sample',
        body: 'Raise the sample size from 10 to 40 — four times as many rolls per average.',
        simulation: 'clt',
        simConfig: { parent: 0, m: 40, samples: 600 },
        question: 'What is the standard error for samples of 40? (decimal)',
        answer: standardError(dieSD(), 40),
        tolerance: 0.05,
        unit: 'standard error',
        feedback: {
          correct: 'Right — 1.71/√40 ≈ 0.27. Quadrupling the sample size halved the spread, since √4 = 2.',
          incorrect: 'Standard error = σ/√m = 1.71/√40 ≈ 0.27 — half of the value for samples of 10.',
        },
      },
      {
        id: 'l9-s5',
        type: 'problem',
        title: 'A tiny sample',
        body: 'Now just 4 rolls per average — a small sample, so the CLT’s bell is wide and a little lumpy.',
        simulation: 'clt',
        simConfig: { parent: 0, m: 4, samples: 600 },
        question: 'What is the standard error for samples of 4? (decimal)',
        answer: standardError(dieSD(), 4),
        tolerance: 0.08,
        unit: 'standard error',
        feedback: {
          correct: 'Yes — 1.71/√4 = 1.71/2 ≈ 0.85. Small samples give wide, bumpy bells.',
          incorrect: 'Standard error = σ/√m = 1.71/√4 = 1.71/2 ≈ 0.85.',
        },
      },
    ],
  },
  {
    id: 'l8-random-walk',
    index: 8,
    title: 'Random Walks',
    concept: 'Drift and the √n spread',
    status: 'built',
    prerequisiteId: 'l9-clt',
    steps: [
      {
        id: 'l8-s1',
        type: 'concept',
        title: 'Watch chance wander',
        body: 'Start at zero and step up or down by one, decided by a coin, over and over. A single walk looks aimless — but launch a crowd of them and a clear pattern appears: the cloud barely drifts, yet it steadily spreads. Run the walk and watch the fan widen.',
        simulation: 'randomWalk',
        simConfig: { steps: 80, p: 0.5 },
        lecture: [
          {
            heading: 'A walk is a running sum',
            text: 'A random walk adds independent $\\pm 1$ steps. After $n$ steps the position $S_n$ is the sum of the individual steps $X_i$, each $+1$ or $-1$. The whole jagged path is just the running total of these coin-flip moves.',
            formula: 'S_n = \\sum_{i=1}^{n} X_i, \\quad X_i \\in \\{+1,\\, -1\\}',
          },
          {
            heading: 'Where it tends to go (drift)',
            text: 'If each step is $+1$ with probability $p$, its average is $2p - 1$. By linearity of expectation the expected position grows linearly. A fair walk ($p = \\tfrac{1}{2}$) has zero drift — on average it goes nowhere at all.',
            formula: 'E[S_n] = n\\,(2p - 1)',
          },
          {
            heading: 'How far it strays (√n)',
            text: 'Going nowhere on average does not mean staying put. Each step adds variance $4p(1-p)$, and the variances of independent steps add, so the standard deviation after $n$ steps is $2\\sqrt{p(1-p)\\,n}$. For a fair walk this is the famous $\\sqrt{n}$: typical distance grows with the square root of the number of steps.',
            formula: '\\operatorname{SD}(S_n) = 2\\sqrt{p(1-p)\\,n} \\;\\xrightarrow{\\,p=1/2\\,}\\; \\sqrt{n}',
          },
          {
            heading: 'The √n trap',
            text: 'Because distance grows like $\\sqrt{n}$, wandering twice as far takes four times as many steps. And a fair walk has no memory: a long run of upward steps does not pull it back down. The cloud spreads — it is never corrected.',
          },
          {
            heading: 'A bell at the end',
            text: 'The final position is a sum of many independent steps, so by the Central Limit Theorem its distribution is approximately normal — centered on the drift $n(2p-1)$ with spread $\\sqrt{n}$ for a fair walk. The fan you see is a bell curve viewed edge-on.',
          },
        ],
      },
      {
        id: 'l8-s6',
        type: 'problem',
        title: 'Sketch where they land',
        body: 'Each step leans: +1 with probability 0.6, −1 with probability 0.4, over 100 steps.',
        simulation: 'randomWalk',
        simConfig: { steps: 100, p: 0.6 },
        question: 'Sketch the distribution of final positions for this biased 100-step walk, then run it to compare.',
        interaction: 'draw',
        drawCategories: walkEndBias.categories,
        answerShape: walkEndBias.shape,
        tolerance: 0.2,
        unit: 'shape',
        feedback: {
          correct: 'Exactly — a bell shifted to about +20 (drift 100·0.2) with spread ≈ 9.8. Drift moves the center; √n sets the width.',
          incorrect: 'The bell centers on the drift 100·(2·0.6−1) = +20, with spread ≈ 9.8 — not on 0.',
        },
      },
      {
        id: 'l8-s2',
        type: 'problem',
        title: 'Where does it end up?',
        body: 'A fair walk takes 100 steps of +1 or −1, each equally likely.',
        simulation: 'randomWalk',
        simConfig: { steps: 100, p: 0.5 },
        question: 'On average, what is the final position after 100 steps? (number of steps from the start)',
        answer: randomWalkDrift(100, 0.5),
        tolerance: 1,
        unit: 'position',
        feedback: {
          correct:
            'Right — a fair walk has zero drift. The cloud of endings is centered on 0, even though almost no single walk lands exactly there.',
          incorrect: 'Each step averages 0, so by linearity the expected position is 100 × 0 = 0.',
        },
      },
      {
        id: 'l8-s3',
        type: 'problem',
        title: 'How far from home?',
        body: 'The expected position is 0 — yet the walks clearly stray from the start. Typical distance is measured by the standard deviation.',
        simulation: 'randomWalk',
        simConfig: { steps: 100, p: 0.5 },
        question: 'About how far from the start is a typical walk after 100 steps? (number of steps)',
        answer: randomWalkRMS(100, 0.5),
        tolerance: 1.5,
        unit: 'distance',
        feedback: {
          correct: 'Exactly — the spread is √100 = 10. Zero on average, yet typically about 10 steps away.',
          incorrect: 'Typical distance is the standard deviation: √n = √100 = 10 steps.',
        },
      },
      {
        id: 'l8-s4',
        type: 'problem',
        title: 'A shorter walk',
        body: 'Now the fair walk takes only 25 steps.',
        simulation: 'randomWalk',
        simConfig: { steps: 25, p: 0.5 },
        question: 'About how far from the start is a typical walk after 25 steps? (number of steps)',
        answer: randomWalkRMS(25, 0.5),
        tolerance: 1,
        unit: 'distance',
        feedback: {
          correct: 'Right — √25 = 5. Fewer steps, a tighter spread.',
          incorrect: 'The typical distance is √n = √25 = 5 steps.',
        },
      },
      {
        id: 'l8-s5',
        type: 'problem',
        title: 'Quadruple the steps',
        body: 'Stretch the fair walk to 400 steps — four times the 100-step walk from before.',
        simulation: 'randomWalk',
        simConfig: { steps: 400, p: 0.5 },
        question: 'About how far from the start is a typical walk after 400 steps? (number of steps)',
        answer: randomWalkRMS(400, 0.5),
        tolerance: 3,
        unit: 'distance',
        feedback: {
          correct: 'Yes — √400 = 20. Four times the steps only doubles the distance, because distance grows like √n.',
          incorrect: 'Typical distance is √n = √400 = 20 — only double the 100-step walk, not quadruple.',
        },
      },
    ],
  },
];

export const FINAL_TEST_ID = 'lf-final-test';

/**
 * The Final Test — a 10-question capstone exam spanning all eight lessons.
 * Unlike a lesson it withholds every result until all ten questions are answered
 * (the deferred-feedback flow lives in `components/TestPlayer.tsx`). The concrete
 * questions are generated from the same parameterized templates as the lessons
 * (registered under `FINAL_TEST_ID` in `problemTemplates.ts`); the static steps
 * below are the fallback content and the source of the gradable slot ids. Kept
 * deliberately out of the `lessons` array so it never distorts course stats —
 * UI surfaces reference `finalTest` directly. Every answer is computed from
 * `probability.ts`.
 */
export const finalTest: Lesson = {
  id: FINAL_TEST_ID,
  index: 9,
  title: 'Final Test',
  concept: 'A 10-question capstone',
  status: 'built',
  prerequisiteId: 'l8-random-walk',
  steps: [
    {
      id: 'lf-s1',
      type: 'problem',
      title: 'Long-run frequency',
      body: 'A fair coin is flipped 1000 times.',
      simulation: 'coinFlip',
      simConfig: { flips: 1000, p: 0.5 },
      question: 'What fraction of the flips come up heads? (decimal)',
      answer: longRunFrequency(0.5),
      tolerance: 0.05,
      unit: 'fraction',
      feedback: {
        correct: 'A fair coin settles on 0.5 over the long run.',
        incorrect: 'Each flip is 50/50, so the long-run fraction is 0.5.',
      },
    },
    {
      id: 'lf-s2',
      type: 'problem',
      title: 'A sum of seven',
      body: 'You roll two fair six-sided dice and add the faces.',
      simulation: 'diceRoll',
      simConfig: { rolls: 2000 },
      question: 'What is the probability the two dice sum to 7? (decimal)',
      answer: dice[7],
      tolerance: 0.02,
      unit: 'probability',
      feedback: {
        correct: 'Six of the 36 outcomes make 7, so 1/6 ≈ 0.167.',
        incorrect: 'There are 6 ways to roll a 7 out of 36 outcomes: 1/6 ≈ 0.167.',
      },
    },
    {
      id: 'lf-s3',
      type: 'problem',
      title: 'The crowded middle',
      body: 'A 12-row Galton board drops balls into 13 bins.',
      simulation: 'galtonBoard',
      simConfig: { rows: 12, balls: 1000 },
      question: 'What fraction of balls land in the three central bins? (decimal)',
      answer: galtonCenterFraction(12, 3),
      tolerance: 0.06,
      unit: 'fraction',
      feedback: {
        correct: 'About 0.61 — the center dominates.',
        incorrect: 'Add the three central binomial probabilities: about 0.61.',
      },
    },
    {
      id: 'lf-s4',
      type: 'problem',
      title: 'A long-shot lottery',
      body: 'A ticket pays $100 with probability 0.1, and nothing otherwise.',
      simulation: 'expectedValue',
      simConfig: wheelConfig(lotteryWheel),
      question: 'What is the expected value of one ticket? (dollars)',
      answer: wheelEV(lotteryWheel),
      tolerance: 1,
      unit: 'dollars',
      feedback: {
        correct: '100 × 0.1 = $10 on average.',
        incorrect: 'Weight the payout by its chance: 100 × 0.1 = $10.',
      },
    },
    {
      id: 'lf-s5',
      type: 'problem',
      title: 'The first card',
      body: 'You draw one card from a freshly shuffled 52-card deck.',
      simulation: 'conditional',
      simConfig: { metric: 0, scaleMax: 0.15, trials: 6000 },
      question: 'What is the probability it is an ace? (decimal)',
      answer: drawProbability(4, 52),
      tolerance: 0.02,
      unit: 'probability',
      feedback: {
        correct: '4 aces in 52 cards is 1/13 ≈ 0.077.',
        incorrect: 'There are 4 aces in 52 cards: 4/52 ≈ 0.077.',
      },
    },
    {
      id: 'lf-s6',
      type: 'problem',
      title: 'Always switching',
      body: 'Three doors, one car. You pick one, the host opens a goat, and you switch.',
      simulation: 'montyHall',
      simConfig: { doors: 3, strategy: 1, trials: 1500 },
      question: 'What fraction of games do you win by switching? (decimal)',
      answer: montyHallSwitchWin(3),
      tolerance: 0.05,
      unit: 'fraction',
      feedback: {
        correct: 'Switching wins whenever your first pick was wrong: 2/3.',
        incorrect: 'Your first pick is wrong 2/3 of the time, so switching wins 2/3.',
      },
    },
    {
      id: 'lf-s7',
      type: 'problem',
      title: 'Standard error',
      body: 'A fair die has standard deviation about 1.71. You average 16 rolls at a time.',
      simulation: 'clt',
      simConfig: { parent: 0, m: 16, samples: 600 },
      question: 'What is the standard error (the SD of the sample mean) for samples of 16? (decimal)',
      answer: standardError(dieSD(), 16),
      tolerance: 0.06,
      unit: 'standard error',
      feedback: {
        correct: '1.71 / √16 ≈ 0.43.',
        incorrect: 'Standard error = σ/√m = 1.71/√16 ≈ 0.43.',
      },
    },
    {
      id: 'lf-s8',
      type: 'problem',
      title: 'How far from home?',
      body: 'A fair walk takes 100 steps of +1 or −1, each equally likely.',
      simulation: 'randomWalk',
      simConfig: { steps: 100, p: 0.5 },
      question: 'About how far from the start is a typical walk after 100 steps? (number of steps)',
      answer: randomWalkRMS(100, 0.5),
      tolerance: 1.5,
      unit: 'distance',
      feedback: {
        correct: 'Typical distance is √100 = 10 steps.',
        incorrect: 'Typical distance is the standard deviation √n = √100 = 10.',
      },
    },
    {
      id: 'lf-s9',
      type: 'problem',
      title: 'Both aces',
      body: 'You draw two cards from a full deck: an ace first, then an ace again.',
      simulation: 'conditional',
      simConfig: { metric: 1, scaleMax: 0.02, trials: 8000 },
      question: 'What is the probability both cards are aces? (decimal)',
      answer: drawMatchesNoReplacement(4, 52, 2),
      tolerance: 0.004,
      unit: 'probability',
      feedback: {
        correct: '(4/52)(3/51) ≈ 0.0045.',
        incorrect: 'Chain the draws: (4/52)(3/51) ≈ 0.0045.',
      },
    },
    {
      id: 'lf-s10',
      type: 'problem',
      title: 'The gambler’s trap',
      body: 'You flip a fair coin and happen to get 6 heads in a row.',
      simulation: 'coinFlip',
      simConfig: { flips: 1000, p: 0.5 },
      question: 'What is the probability the very next flip is heads? (decimal)',
      answer: longRunFrequency(0.5),
      tolerance: 0.05,
      unit: 'probability',
      feedback: {
        correct: 'Independence means past streaks don’t matter — still 0.5.',
        incorrect: 'A fair coin has no memory; the next flip is still 0.5.',
      },
    },
  ],
};

export function getLesson(id: string): Lesson | undefined {
  return lessons.find((l) => l.id === id);
}

export function gradableSteps(lesson: Lesson) {
  return lesson.steps.filter((s) => s.type === 'problem');
}
