import type { Lesson } from '../types/lesson';
import {
  normalCdf,
  normalTwoTail,
  zScore,
  chebyshevBound,
  normalApproxBinomialAtMost,
  normalApproxBinomialBetween,
} from '../lib/probability';

export const limitLessons: Lesson[] = [
  {
    id: 's6-empirical-rule',
    index: 0,
    title: 'Empirical Rule & z-scores',
    concept: '68–95–99.7 and standardizing',
    status: 'built',
    prerequisiteId: null,
    steps: [
      {
        id: 's6-empirical-rule-s1',
        type: 'concept',
        title: 'The shape of the bell',
        body: 'Normal data clusters predictably around the mean. About 68% lands within one standard deviation, 95% within two, and 99.7% within three. A z-score says how many SDs from the mean a value sits.',
        simulation: 'clt',
        simConfig: { parent: 0, m: 10, samples: 600 },
        lecture: [
          {
            heading: 'The empirical rule',
            text: 'For a roughly normal distribution, fixed fractions fall within 1, 2, and 3 standard deviations of the mean.',
            formula: '68\\% \\;/\\; 95\\% \\;/\\; 99.7\\%',
          },
          {
            heading: 'z-scores',
            text: 'Standardizing rescales any value to standard-deviation units, so different normals become comparable.',
            formula: 'z = \\frac{x - \\mu}{\\sigma}',
          },
          {
            heading: 'Common mistake',
            text: 'The rule applies to roughly normal data. Heavily skewed data does not obey 68–95–99.7.',
          },
        ],
      },
      {
        id: 's6-empirical-rule-s2',
        type: 'problem',
        title: 'Within one SD',
        body: 'A measurement is normally distributed.',
        question: 'What fraction of values fall within 1 SD of the mean? (decimal)',
        answer: normalCdf(1) - normalCdf(-1),
        tolerance: 0.03,
        unit: 'fraction',
        feedback: {
          correct: 'Right — about 0.68.',
          incorrect: 'The empirical rule gives ≈ 0.68 within 1 SD.',
        },
      },
      {
        id: 's6-empirical-rule-s3',
        type: 'problem',
        title: 'Within two SD',
        body: 'Same normal measurement.',
        question: 'What fraction fall within 2 SD of the mean? (decimal)',
        answer: normalCdf(2) - normalCdf(-2),
        tolerance: 0.03,
        unit: 'fraction',
        feedback: {
          correct: 'Right — about 0.95.',
          incorrect: 'About 0.95 of values fall within 2 SD.',
        },
      },
      {
        id: 's6-empirical-rule-s4',
        type: 'problem',
        title: 'In the tails',
        body: 'Same normal measurement.',
        question: 'What fraction fall MORE than 2 SD from the mean? (decimal)',
        answer: normalTwoTail(2),
        tolerance: 0.02,
        unit: 'fraction',
        feedback: {
          correct: 'Right — about 0.045 (1 − 0.95) sits in the two tails.',
          incorrect: 'Outside 2 SD is 1 − 0.95 ≈ 0.045.',
        },
      },
      {
        id: 's6-empirical-rule-s5',
        type: 'problem',
        title: 'A z-score',
        body: 'Test scores have mean 70 and standard deviation 10. You scored 85.',
        question: 'What is your z-score? (a number)',
        answer: zScore(85, 70, 10),
        tolerance: 0.05,
        unit: 'z',
        feedback: {
          correct: 'Right — (85 − 70)/10 = 1.5 SD above the mean.',
          incorrect: 'z = (x − μ)/σ = (85 − 70)/10 = 1.5.',
        },
      },
      {
        id: 's6-empirical-rule-s6',
        type: 'problem',
        title: 'A percentile',
        body: 'A value sits exactly 1 SD above the mean of a normal distribution.',
        question: 'What fraction of values are below it? (decimal)',
        answer: normalCdf(1),
        tolerance: 0.02,
        unit: 'fraction',
        feedback: {
          correct: 'Right — Φ(1) ≈ 0.841, the 84th percentile.',
          incorrect: 'P(Z < 1) = Φ(1) ≈ 0.841.',
        },
      },
    ],
  },
  {
    id: 's6-normal-approx',
    index: 0,
    title: 'Normal Approximation to the Binomial',
    concept: 'Bell curve for counts',
    status: 'built',
    prerequisiteId: null,
    steps: [
      {
        id: 's6-normal-approx-s1',
        type: 'concept',
        title: 'Smoothing the bars',
        body: 'For large n a binomial looks like a normal curve with mean np and SD √(np(1−p)). Match those and use the normal — with a half-step continuity correction.',
        simulation: 'galtonBoard',
        simConfig: { rows: 12, balls: 300 },
        lecture: [
          {
            heading: 'Matching the moments',
            text: 'Approximate Binomial$(n,p)$ by a normal with the same mean and standard deviation.',
            formula: '\\mu = np, \\quad \\sigma = \\sqrt{np(1-p)}',
          },
          {
            heading: 'Continuity correction',
            text: 'Because the binomial is discrete, widen each integer by half a unit before applying the normal CDF.',
            formula: 'P(X \\le k) \\approx \\Phi\\!\\left(\\tfrac{k + 0.5 - \\mu}{\\sigma}\\right)',
          },
          {
            heading: 'Common mistake',
            text: 'The approximation needs $np$ and $n(1-p)$ both large. For small n or extreme p, use the exact binomial.',
          },
        ],
      },
      {
        id: 's6-normal-approx-s2',
        type: 'problem',
        title: 'At most 45',
        body: '100 fair coin flips (n = 100, p = 0.5): mean 50, SD 5.',
        question: 'Approximate P(K ≤ 45) using the normal. (decimal)',
        answer: normalApproxBinomialAtMost(100, 0.5, 45),
        tolerance: 0.03,
        unit: 'probability',
        feedback: {
          correct: 'Right — Φ((45.5 − 50)/5) = Φ(−0.9) ≈ 0.184.',
          incorrect: 'With continuity: Φ((45.5 − 50)/5) = Φ(−0.9) ≈ 0.184.',
        },
      },
      {
        id: 's6-normal-approx-s3',
        type: 'problem',
        title: 'A central band',
        body: 'Same 100 flips (mean 50, SD 5).',
        question: 'Approximate P(45 ≤ K ≤ 55). (decimal)',
        answer: normalApproxBinomialBetween(100, 0.5, 45, 55),
        tolerance: 0.03,
        unit: 'probability',
        feedback: {
          correct: 'Right — Φ(1.1) − Φ(−1.1) ≈ 0.73.',
          incorrect: 'Φ((55.5 − 50)/5) − Φ((44.5 − 50)/5) = Φ(1.1) − Φ(−1.1) ≈ 0.73.',
        },
      },
      {
        id: 's6-normal-approx-s4',
        type: 'problem',
        title: 'An upper tail',
        body: 'Same 100 flips (mean 50, SD 5).',
        question: 'Approximate P(K ≥ 60). (decimal)',
        answer: 1 - normalApproxBinomialAtMost(100, 0.5, 59),
        tolerance: 0.02,
        unit: 'probability',
        feedback: {
          correct: 'Right — 1 − Φ((59.5 − 50)/5) = 1 − Φ(1.9) ≈ 0.029.',
          incorrect: 'P(K ≥ 60) = 1 − Φ(1.9) ≈ 0.029.',
        },
      },
      {
        id: 's6-normal-approx-s5',
        type: 'problem',
        title: 'More flips, tighter fit',
        body: '400 fair flips (n = 400, p = 0.5): mean 200, SD 10.',
        question: 'Approximate P(K ≤ 190). (decimal)',
        answer: normalApproxBinomialAtMost(400, 0.5, 190),
        tolerance: 0.03,
        unit: 'probability',
        feedback: {
          correct: 'Right — Φ((190.5 − 200)/10) = Φ(−0.95) ≈ 0.171.',
          incorrect: 'Φ((190.5 − 200)/10) = Φ(−0.95) ≈ 0.171.',
        },
      },
    ],
  },
  {
    id: 's6-chebyshev',
    index: 0,
    title: 'Chebyshev’s Inequality',
    concept: 'A universal tail bound',
    status: 'built',
    prerequisiteId: null,
    steps: [
      {
        id: 's6-chebyshev-s1',
        type: 'concept',
        title: 'A bound for any distribution',
        body: 'Without knowing the shape, Chebyshev caps how much probability can sit far from the mean: at most 1/k² beyond k standard deviations. For a normal it is wildly loose — sample the tails and compare.',
        simulation: 'tailBound',
        simConfig: { k: 2, trials: 5000 },
        lecture: [
          {
            heading: 'Chebyshev’s inequality',
            text: 'For any distribution with finite variance, the probability of landing at least $k$ standard deviations from the mean is bounded.',
            formula: 'P(|X - \\mu| \\ge k\\sigma) \\le \\frac{1}{k^2}',
          },
          {
            heading: 'Distribution-free but loose',
            text: 'The bound holds for every distribution, which makes it pessimistic for nice ones. A normal keeps only ≈ 4.5% beyond 2 SD, far under the 25% bound.',
          },
          {
            heading: 'Common mistake',
            text: 'Chebyshev gives an upper bound, not the actual probability. Use it when the distribution is unknown.',
          },
        ],
      },
      {
        id: 's6-chebyshev-s2',
        type: 'problem',
        title: 'The bound at k = 2',
        body: 'Apply Chebyshev with k = 2 standard deviations.',
        question: 'What is the Chebyshev upper bound on P(|X − μ| ≥ 2σ)? (decimal)',
        answer: chebyshevBound(2),
        tolerance: 0.02,
        unit: 'bound',
        feedback: {
          correct: 'Right — 1/2² = 0.25.',
          incorrect: 'The bound is 1/k² = 1/4 = 0.25.',
        },
      },
      {
        id: 's6-chebyshev-s3',
        type: 'problem',
        title: 'The bound at k = 3',
        body: 'Apply Chebyshev with k = 3.',
        question: 'What is the Chebyshev bound on P(|X − μ| ≥ 3σ)? (decimal)',
        answer: chebyshevBound(3),
        tolerance: 0.02,
        unit: 'bound',
        feedback: {
          correct: 'Right — 1/9 ≈ 0.111.',
          incorrect: 'The bound is 1/k² = 1/9 ≈ 0.111.',
        },
      },
      {
        id: 's6-chebyshev-s4',
        type: 'problem',
        title: 'The actual normal tail',
        body: 'Now sample a standard normal and look beyond ±2 SD.',
        simulation: 'tailBound',
        simConfig: { k: 2, trials: 8000 },
        question: 'What fraction of a normal lies beyond 2 SD? (decimal)',
        answer: normalTwoTail(2),
        tolerance: 0.02,
        unit: 'fraction',
        feedback: {
          correct: 'Right — only ≈ 0.045, far below Chebyshev’s 0.25.',
          incorrect: 'For a normal it is ≈ 0.045 — the bound (0.25) is very loose.',
        },
      },
      {
        id: 's6-chebyshev-s5',
        type: 'problem',
        title: 'Beyond three SD',
        body: 'Sample a standard normal and look beyond ±3 SD.',
        simulation: 'tailBound',
        simConfig: { k: 3, trials: 20000 },
        question: 'What fraction of a normal lies beyond 3 SD? (decimal)',
        answer: normalTwoTail(3),
        tolerance: 0.01,
        unit: 'fraction',
        feedback: {
          correct: 'Right — about 0.0027, the famous 99.7% rule’s leftover.',
          incorrect: 'About 0.0027 lies beyond 3 SD (the 99.7% rule).',
        },
      },
    ],
  },
];
