import type { Lesson } from '../types/lesson';
import type { WheelSegment } from '../lib/probability';
import {
  stddev,
  expectedFixedPoints,
  expectedIndicatorSum,
  expectedRollsUntilFace,
  expectedTrialsGeometric,
  expectedConsecutive,
} from '../lib/probability';
import { wheelConfig } from './simData';

const dieSegments: WheelSegment[] = [1, 2, 3, 4, 5, 6].map((v) => ({ value: v, p: 1 / 6 }));
const coin2: WheelSegment[] = [
  { value: 2, p: 0.5 },
  { value: 0, p: 0.5 },
];
const coin4: WheelSegment[] = [
  { value: 4, p: 0.5 },
  { value: 0, p: 0.5 },
];
const risky: WheelSegment[] = [
  { value: 5, p: 0.2 },
  { value: 0, p: 0.8 },
];
const bernoulli: WheelSegment[] = [
  { value: 1, p: 0.5 },
  { value: 0, p: 0.5 },
];

/** Variance/SD sim: spin the wheel, show the ±σ spread band. */
const spreadCfg = (segs: WheelSegment[]) => ({ ...wheelConfig(segs), spread: 1 });

export const rvLessons: Lesson[] = [
  {
    id: 's4-variance',
    index: 0,
    title: 'Variance & Standard Deviation',
    concept: 'Measuring spread',
    status: 'built',
    prerequisiteId: null,
    steps: [
      {
        id: 's4-variance-s1',
        type: 'concept',
        title: 'How far outcomes spread',
        body: 'Two games can share an expected value yet feel completely different — one steady, one wild. Variance measures that spread; standard deviation puts it back in the original units. Spin the wheel and watch the ±σ band widen around the running average.',
        simulation: 'expectedValue',
        simConfig: spreadCfg(dieSegments),
        lecture: [
          {
            heading: 'Variance',
            text: 'Variance is the expected squared distance from the mean. The shortcut $E[X^2] - (E[X])^2$ is usually easiest to compute.',
            formula: '\\operatorname{Var}(X) = E[(X-\\mu)^2] = E[X^2] - \\mu^2',
          },
          {
            heading: 'Standard deviation',
            text: 'Standard deviation is the square root of variance, returning to the units of $X$ so it reads as a typical distance from the mean.',
            formula: '\\sigma = \\sqrt{\\operatorname{Var}(X)}',
          },
          {
            heading: 'Scaling',
            text: 'Multiplying every payoff by $a$ multiplies the standard deviation by $|a|$ and the variance by $a^2$.',
            formula: '\\operatorname{Var}(aX) = a^2 \\operatorname{Var}(X)',
          },
          {
            heading: 'Common mistake',
            text: 'Equal means do not mean equal risk. Always compare spread, not just the average.',
          },
        ],
      },
      {
        id: 's4-variance-s2',
        type: 'problem',
        title: 'A simple coin game',
        body: 'A game pays $2 on heads and $0 on tails (fair coin). Spin to watch the spread.',
        simulation: 'expectedValue',
        simConfig: spreadCfg(coin2),
        question: 'What is the standard deviation of the payout? (dollars)',
        answer: stddev(coin2),
        tolerance: 0.15,
        unit: 'SD',
        feedback: {
          correct: 'Right — mean 1, E[X²] = 2, variance 1, so σ = 1.',
          incorrect: 'Var = E[X²] − μ² = 2 − 1 = 1, so σ = 1.',
        },
      },
      {
        id: 's4-variance-s3',
        type: 'problem',
        title: 'A fair die',
        body: 'A die pays its face value in dollars.',
        simulation: 'expectedValue',
        simConfig: spreadCfg(dieSegments),
        question: 'What is the standard deviation of the payout? (dollars)',
        answer: stddev(dieSegments),
        tolerance: 0.2,
        unit: 'SD',
        feedback: {
          correct: 'Exactly — Var = 35/12 ≈ 2.92, so σ ≈ 1.71.',
          incorrect: 'E[X²] = 91/6, μ = 3.5, Var = 91/6 − 12.25 = 35/12, σ ≈ 1.71.',
        },
      },
      {
        id: 's4-variance-s4',
        type: 'problem',
        title: 'A riskier bet',
        body: 'A bet pays $5 with probability 0.2 and $0 otherwise.',
        simulation: 'expectedValue',
        simConfig: spreadCfg(risky),
        question: 'What is the standard deviation of the payout? (dollars)',
        answer: stddev(risky),
        tolerance: 0.2,
        unit: 'SD',
        feedback: {
          correct: 'Right — mean 1, E[X²] = 5, variance 4, so σ = 2.',
          incorrect: 'Var = 25(0.2) − 1² = 5 − 1 = 4, so σ = 2.',
        },
      },
      {
        id: 's4-variance-s5',
        type: 'problem',
        title: 'Double the stakes',
        body: 'Now the coin game pays $4 on heads and $0 on tails.',
        simulation: 'expectedValue',
        simConfig: spreadCfg(coin4),
        question: 'What is the standard deviation? (dollars)',
        answer: stddev(coin4),
        tolerance: 0.2,
        unit: 'SD',
        feedback: {
          correct: 'Right — σ = 2, exactly double the $2 game. Scaling payouts by 2 doubles the SD.',
          incorrect: 'Scaling payouts by 2 doubles σ: from 1 to 2.',
        },
      },
      {
        id: 's4-variance-s6',
        type: 'problem',
        title: 'A single Bernoulli',
        body: 'Let X be 1 if a fair coin lands heads, 0 otherwise. Spin to see the spread.',
        simulation: 'expectedValue',
        simConfig: spreadCfg(bernoulli),
        question: 'What is the standard deviation of X? (decimal)',
        answer: stddev(bernoulli),
        tolerance: 0.08,
        unit: 'SD',
        feedback: {
          correct: 'Right — σ = √(p(1−p)) = √0.25 = 0.5.',
          incorrect: 'σ = √(p(1−p)) = √0.25 = 0.5.',
        },
      },
    ],
  },
  {
    id: 's4-indicators',
    index: 0,
    title: 'Indicators & Expected Counts',
    concept: 'Linearity counts events',
    status: 'built',
    prerequisiteId: null,
    steps: [
      {
        id: 's4-indicators-s1',
        type: 'concept',
        title: 'Add up the chances',
        body: 'To find the expected number of events that happen, add their individual probabilities — even when the events influence each other. Shuffle the hats and watch the average number of matches sit at exactly 1.',
        simulation: 'matching',
        simConfig: { n: 6, metric: 1, trials: 4000 },
        lecture: [
          {
            heading: 'Indicator variables',
            text: 'An indicator $I_A$ is 1 when event $A$ happens and 0 otherwise, so its expected value is just $P(A)$.',
            formula: 'E[I_A] = P(A)',
          },
          {
            heading: 'Linearity of expectation',
            text: 'The expected number of events that occur is the sum of their probabilities. Linearity holds even when the events are dependent — no independence required.',
            formula: 'E\\!\\left[\\sum_i I_{A_i}\\right] = \\sum_i P(A_i)',
          },
          {
            heading: 'Common mistake',
            text: 'Dependence changes the variance of the count, not its expectation. You never need independence to add the probabilities.',
          },
        ],
      },
      {
        id: 's4-indicators-s2',
        type: 'problem',
        title: 'Hat matches',
        body: 'Six hats are returned at random.',
        simulation: 'matching',
        simConfig: { n: 6, metric: 1, trials: 5000 },
        question: 'What is the expected number of people who get their own hat? (a number)',
        answer: expectedFixedPoints(6),
        tolerance: 0.12,
        unit: 'matches',
        feedback: {
          correct: 'Right — each of the 6 matches with probability 1/6, summing to 1.',
          incorrect: 'Sum the indicators: 6 × (1/6) = 1.',
        },
      },
      {
        id: 's4-indicators-s3',
        type: 'problem',
        title: 'Sixes in 12 rolls',
        body: 'You roll a fair die 12 times.',
        question: 'What is the expected number of sixes? (a number)',
        answer: expectedIndicatorSum(Array(12).fill(1 / 6)),
        tolerance: 0.1,
        unit: 'sixes',
        feedback: {
          correct: 'Right — 12 × (1/6) = 2.',
          incorrect: 'Each roll is a six with probability 1/6: 12 × 1/6 = 2.',
        },
      },
      {
        id: 's4-indicators-s4',
        type: 'problem',
        title: 'Heads in 20 flips',
        body: 'You flip a biased coin (P(heads) = 0.3) twenty times.',
        question: 'What is the expected number of heads? (a number)',
        answer: expectedIndicatorSum(Array(20).fill(0.3)),
        tolerance: 0.2,
        unit: 'heads',
        feedback: {
          correct: 'Right — 20 × 0.3 = 6.',
          incorrect: 'Sum the per-flip probabilities: 20 × 0.3 = 6.',
        },
      },
      {
        id: 's4-indicators-s5',
        type: 'problem',
        title: 'Red cards in a hand',
        body: 'You deal a 5-card hand from a standard deck (26 of 52 cards are red).',
        question: 'What is the expected number of red cards? (a number)',
        answer: expectedIndicatorSum(Array(5).fill(0.5)),
        tolerance: 0.1,
        unit: 'red cards',
        feedback: {
          correct: 'Right — 5 × (26/52) = 2.5, even though the draws are dependent.',
          incorrect: 'Linearity ignores dependence: 5 × 0.5 = 2.5.',
        },
      },
    ],
  },
  {
    id: 's4-first-step',
    index: 0,
    title: 'Waiting Times by First-Step',
    concept: 'Expected steps to an event',
    status: 'built',
    prerequisiteId: null,
    steps: [
      {
        id: 's4-first-step-s1',
        type: 'concept',
        title: 'How long until it happens?',
        body: 'Repeating a chance experiment until something occurs has a predictable average length. Run the trials and watch the average number of steps settle.',
        simulation: 'expectedSteps',
        simConfig: { kind: 0, faces: 6, trials: 2000 },
        lecture: [
          {
            heading: 'First-step analysis',
            text: 'Let $E$ be the expected number of steps. Conditioning on the first step gives a one-line equation you can solve for $E$.',
            formula: 'E = 1 + (1-p)\\,E \\;\\Rightarrow\\; E = \\tfrac{1}{p}',
          },
          {
            heading: 'Waiting for a success',
            text: 'For an event with probability $p$ each trial, the expected wait to the first success is $1/p$ — six rolls for a particular die face, two flips for a fair coin.',
          },
          {
            heading: 'Common mistake',
            text: 'Compound goals are not simply $1/p$. Waiting for two of a kind in a row needs a recursion and is much longer.',
          },
        ],
      },
      {
        id: 's4-first-step-s2',
        type: 'problem',
        title: 'Rolling a six',
        body: 'You roll a fair die until a six appears.',
        simulation: 'expectedSteps',
        simConfig: { kind: 0, faces: 6, trials: 4000 },
        question: 'What is the expected number of rolls? (a number)',
        answer: expectedRollsUntilFace(6),
        tolerance: 0.6,
        unit: 'rolls',
        feedback: {
          correct: 'Right — 1/(1/6) = 6.',
          incorrect: 'The wait to a 1/6 event is 1/p = 6 rolls.',
        },
      },
      {
        id: 's4-first-step-s3',
        type: 'problem',
        title: 'First head',
        body: 'You flip a fair coin until heads appears.',
        simulation: 'expectedSteps',
        simConfig: { kind: 1, p: 0.5, trials: 4000 },
        question: 'What is the expected number of flips? (a number)',
        answer: expectedTrialsGeometric(0.5),
        tolerance: 0.4,
        unit: 'flips',
        feedback: {
          correct: 'Right — 1/0.5 = 2.',
          incorrect: 'Expected wait is 1/p = 1/0.5 = 2.',
        },
      },
      {
        id: 's4-first-step-s4',
        type: 'problem',
        title: 'A rarer success',
        body: 'A machine succeeds with probability 0.25 each try; you repeat until it works.',
        simulation: 'expectedSteps',
        simConfig: { kind: 1, p: 0.25, trials: 5000 },
        question: 'What is the expected number of tries? (a number)',
        answer: expectedTrialsGeometric(0.25),
        tolerance: 0.6,
        unit: 'tries',
        feedback: {
          correct: 'Right — 1/0.25 = 4.',
          incorrect: 'Expected wait is 1/p = 1/0.25 = 4.',
        },
      },
      {
        id: 's4-first-step-s5',
        type: 'problem',
        title: 'Two sixes in a row',
        body: 'You roll a fair die until you get two sixes in a row.',
        simulation: 'expectedSteps',
        simConfig: { kind: 2, faces: 6, run: 2, trials: 6000, scaleMax: 80 },
        question: 'What is the expected number of rolls? (a number)',
        answer: expectedConsecutive(6, 2),
        tolerance: 4,
        unit: 'rolls',
        feedback: {
          correct: 'Right — 6 + 6² = 42, far more than 12. The recursion punishes the streak.',
          incorrect: 'First-step recursion gives 6 + 6² = 42, not 12.',
        },
      },
    ],
  },
  {
    id: 's4-correlation',
    index: 0,
    title: 'Joint Distribution & Correlation',
    concept: 'How two variables move',
    status: 'built',
    prerequisiteId: null,
    steps: [
      {
        id: 's4-correlation-s1',
        type: 'concept',
        title: 'Reading a cloud',
        body: 'When two quantities vary together, the scatter tilts. Correlation r measures that tilt from −1 to +1. Generate clouds and estimate r by eye.',
        simulation: 'scatter',
        simConfig: { rho: 0.6, n: 220 },
        lecture: [
          {
            heading: 'Covariance and correlation',
            text: 'Covariance measures whether two variables move together; correlation standardizes it to a unitless number between −1 and 1.',
            formula: 'r = \\frac{\\operatorname{Cov}(X,Y)}{\\sigma_X \\sigma_Y}',
          },
          {
            heading: 'What r means',
            text: 'Near $+1$ the points hug an upward line; near $-1$, a downward line; near $0$, a shapeless blob. Independence forces $r = 0$.',
          },
          {
            heading: 'Common mistake',
            text: 'Correlation is not causation, and $r = 0$ only rules out a linear trend — a strong curved relationship can still have $r \\approx 0$.',
          },
        ],
      },
      {
        id: 's4-correlation-s2',
        type: 'problem',
        title: 'A tight upward cloud',
        body: 'The points rise together along a clear line.',
        simulation: 'scatter',
        simConfig: { rho: 0.8, n: 250 },
        question: 'Estimate the correlation r. (decimal between −1 and 1)',
        answer: 0.8,
        tolerance: 0.18,
        unit: 'correlation',
        feedback: {
          correct: 'Right — a tight upward tilt is about r ≈ 0.8.',
          incorrect: 'A strong, narrow upward cloud is near r ≈ 0.8.',
        },
      },
      {
        id: 's4-correlation-s3',
        type: 'problem',
        title: 'A downward cloud',
        body: 'Now the points fall as you move right.',
        simulation: 'scatter',
        simConfig: { rho: -0.8, n: 250 },
        question: 'Estimate the correlation r. (decimal)',
        answer: -0.8,
        tolerance: 0.18,
        unit: 'correlation',
        feedback: {
          correct: 'Right — a tight downward tilt is about r ≈ −0.8.',
          incorrect: 'Downward trend means negative r, here about −0.8.',
        },
      },
      {
        id: 's4-correlation-s4',
        type: 'problem',
        title: 'A shapeless blob',
        body: 'The points show no tilt at all.',
        simulation: 'scatter',
        simConfig: { rho: 0, n: 250 },
        question: 'Estimate the correlation r. (decimal)',
        answer: 0,
        tolerance: 0.18,
        unit: 'correlation',
        feedback: {
          correct: 'Right — no trend means r ≈ 0 (independent here).',
          incorrect: 'A round, untilted blob has r ≈ 0.',
        },
      },
      {
        id: 's4-correlation-s5',
        type: 'problem',
        title: 'A loose downward trend',
        body: 'The points drift downward but scatter widely.',
        simulation: 'scatter',
        simConfig: { rho: -0.3, n: 250 },
        question: 'Estimate the correlation r. (decimal)',
        answer: -0.3,
        tolerance: 0.2,
        unit: 'correlation',
        feedback: {
          correct: 'Right — a weak downward tilt is about r ≈ −0.3.',
          incorrect: 'A loose downward drift is a small negative r, near −0.3.',
        },
      },
    ],
  },
];
